### ISSUE TITLE
Add or Link icons to One UI's core apps

### ISSUE THREAD

**Issue by rufus582** [LawnchairLauncher/lawnicons#10]
If would be great if u could add icons for all OEM's core apps, such as phone, messages, gallery and camera. If not, atleast link existing icons for Google apps, to these other OEM's apps😊

**Comment by paphonb** [comment]
Please provide the package name for these apps. We can't add icons if we don't know the apps.

**Comment by rufus582** [comment]
> Please provide the package name for these apps.

Sure. Here they are. These are for Samsung's One UI by the way😊

**Core apps, that badly need themed icons😑👇**
**Samsung Phone:** com.samsung.android.dialer
**Samsung Messages:** com.samsung.android.messaging
**Samsung Gallery:** com.sec.android.gallery3d
**Samsung Camera:** com.sec.android.app.camera
**Samsung My Files:** com.sec.android.app.myfiles

**Other Samsung Stock apps, that I'd love to have themed icons👇**
**Samsung Internet:** com.sec.android.app.sbrowser
**Samsung Notes:** com.samsung.android.app.notes
**Samsung Calculator:** com.sec.android.app.popupcalculator
**Samsung Weather:** com.sec.android.daemonapp
**Samsung Galaxy Store:** com.sec.android.app.samsungapps

**Comment by rufus582** [comment]
Thanks for theming most of the apps😊. But I see that Gallery is unthemed still🤔, and it's one of my most used apps. I'll close this issue once it is also themed...

And can I post 1 more 3rd party app that I'd like to be themed?🥺

**Comment by rufus582** [comment]
Okay. So since Gallery app has been themed now, I'll close this issue now. But before I close. I want to let u guys know that my support and best wishes to u guys, to release lawnchair to the play store❤❤❤
I hope this happens before the end of 2021, or by early 2022😊🤞
@paphonb 

P.S: That 3rd party app I wanted themed is tasker. It's package name is: net.dinglisch.android.taskerm

**Comment by patrykmichalik** [comment]
Thanks for your support, @rufus582! I’ll add icons for Tasker and the remaining One UI system apps shortly.

**Comment by rufus582** [comment]
Sure👍. Also, try to add Mi Fit app too(com.xiaomi.hm.health). Sorry if I am asking for too much😔, but thanks again for your quick support❤

**Comment by patrykmichalik** [comment]
It’s my pleasure! And sure, I’ll add an icon for Mi Fit.
