### ISSUE TITLE
Add Lawncions to Crowdin Organisation for translations

### ISSUE THREAD

**Issue by Chefski** [LawnchairLauncher/lawnicons#1095]
### About this discussion

Add the Lawnicons repository to the [Lawnchair Crowdin organisation](https://lawnchair.crowdin.com/).

**Comment by daywalk3r666** [comment]
+1

**Comment by x9136** [comment]
Apparently those who have time to do this don't have permissions, otherwise it's odd that it hasn't happened yet.
