### ISSUE TITLE
Phone themed icon is not applying properly

### ISSUE THREAD

**Issue by Rixon46** [LawnchairLauncher/lawnicons#11]
it's not showing phone app icon instead of that it's showing contact app icon 

rom: miui 12 based on android 9

**Comment by rufus582** [comment]
Did u try it with Google phone app or MiUi phone app?
I don't think lawnicons work for non-Google, OEM apps yet...

**Comment by Rixon46** [comment]
Miui phone app

**Comment by paphonb** [comment]
What's the package name and component name of the phone app?

**Comment by Rixon46** [comment]
![IMG_20211105_174339](https://user-images.githubusercontent.com/69071330/140508580-04b0c62e-4d52-4095-9af3-d2eb4e310024.jpg)

You mean this one bro ???

**Comment by Rixon46** [comment]
> What's the package name and component name of the phone app?

Bro dev build #593 fixed this issue bro thanks for the fix and i have one more request bro if possible add YouTube vanced music support for themed icon
