### ISSUE TITLE
Request for linking Phone icon to huawei phone app(com.android.incallui) 

### ISSUE THREAD

**Issue by Yurieaijoker** [LawnchairLauncher/lawnicons#110]
Link com.android.incallui to @drawable/dialer please. Thank you

**Comment by patrykmichalik** [comment]
Hello! I’ve just linked the dialer icon to the “com.android.incallui” package.

**Comment by Yurieaijoker** [comment]
Thank you

**Comment by Yurieaijoker** [comment]
Please also link

dialer icon to "com.android.phone" & "com.android.contacts.activities.DialtactsActivity"

Thank you

**Comment by patrykmichalik** [comment]
Done!

**Comment by Yurieaijoker** [comment]
Thanks
