### ISSUE TITLE
Add Instander Icons

### ISSUE THREAD

**Issue by nathww** [LawnchairLauncher/lawnicons#112]
please add instander clone icons

**Comment by lawnchairci** [comment]
Hello! It would appear that this icon request doesnʼt include the package names of some or all of the apps for which icons have been requested. In addition, we are switching to a new system for icon requests. The apps for which package names have been provided (if such apps exist in this icon request) have been added to the new icon request database, meaning no action is required. For the apps for which package names havenʼt been provided, please submit an icon request via the new icon request form: https://forms.gle/Fx8vZAiWdW1Tyjo57.
