### ISSUE TITLE
[DISCUSSION] Document icontool.py in the contributing guide

### ISSUE THREAD

**Issue by thismoon** [LawnchairLauncher/lawnicons#1134]
### About this discussion

A tutorial/guide for using icontool.py should be added to CONTRIBUTING.md
I want to help but i'm not good at writing documentation

**Comment by Chefski** [comment]
Hey! Do you have Discord or Telegram for some communication?

**Comment by Chefski** [comment]
@thismoon mind checking out #1149 and telling me if I'm missing anything? You can also suggest some changes to it.

**Comment by thismoon** [comment]
> Hey! Do you have Discord or Telegram for some communication? @thismoon

Hi @Chefski I'm `إلياس#7329` on discord, and i am already in the lawnchair server.

**Comment by KevoM** [comment]
Having trouble to contribute despite reading the guide. I have some icons ready for PR but don't know how to proceed (ie which 'svgs folder' ? A copy from here ? Should I clone something ? icontools script returns missing files, so I guess I should clone, then when and where to upload the new and edited files ? ;)

**Comment by KevoM** [comment]
> Is this referring to unclear instructions in the icontool guide or the contributing guide? @KevoM

Hi, I was referring to the contributing guide. For now I have succeeded to update locally appfilter.xml + svgs folder.
Maybe it could be useful to indicate for neophytes to clone first. Then I don't know, I did a pull request (41 icons) but I might have done something wrong 

https://github.com/LawnchairLauncher/lawnicons/pull/1165 😰😰😰😰
