### ISSUE TITLE
Lawnicon app displays icons as distorted and out of shape

### ISSUE THREAD

**Issue by thekeyboardworrier** [LawnchairLauncher/lawnicons#1235]
### About this discussion

Lawnicon displays icons in the icon grid view incorrectly. Some icons render with thick strokes and for some of them, it's too narrow. But scrolling them out of the display and back in re-renders them correctly (Image 3).

If you want to reproduce this bug, try typing something in the app search box. Some of the icon in search result shows incorrectly. Clearing the search box also shows some of the icons with incorrect stroke sizes.

Image 1
![MuMu20230514094512](https://github.com/LawnchairLauncher/lawnicons/assets/67034266/212f4774-f6f0-4372-bc7b-a4ea48e3d8d3)

Image 2
![MuMu20230514094738](https://github.com/LawnchairLauncher/lawnicons/assets/67034266/ba9749ad-2c35-469a-a7b2-9364ee69dfb8)

Image 3
![MuMu20230514094713](https://github.com/LawnchairLauncher/lawnicons/assets/67034266/c5f08560-8aab-4c54-b577-f9570f5a94aa)

**Comment by Chefski** [comment]
I believe this issue has been fixed now as I can't replicate it. Feel free to re-open the issue if you still experience this.
