### ISSUE TITLE
[BUG] Themed Clock icon not working in Android 11 - Lineage OS 18.1 

### ISSUE THREAD

**Issue by ghost** [LawnchairLauncher/lawnicons#1238]
### About this discussion

Lawnchair: 12.1 Alpha 4
Lawnicons: 2.1.0
Icon: Clock (com.android.deskclock)

I also checked with Simple Clock (com.simplemobiletools.clock) and and same behavior.

Clock icon works as a normal icon:

![Screenshot_20230514-191301_Lawnchair](https://github.com/LawnchairLauncher/lawnicons/assets/67786790/6eded566-e7f0-4c86-808b-c2fc142acd22)

But when Themed icons in home and app drawer is selected, it doesn't work:

![Screenshot_20230514-191424_Lawnchair](https://github.com/LawnchairLauncher/lawnicons/assets/67786790/c293191e-d6e1-49be-9a17-99198a743dca)

**Comment by chipotledonut** [comment]
Still not working in 2.2.0 @SuperDragonXD

**Comment by W1zardK1ng** [comment]
Have the same issue, it looks very bad when one app icon shows different colour.
Always need to force stop the Lawnchair and change the icon pack and choose lawnicon again to fix this, bit annoying to do this every single time after changing wallpaper.

**Comment by x9136** [comment]
I suggest installing [Lawnchair 14 Beta 2](https://lawnchair.app/downloads/), the latest version of Lawnicons, and let us know if the problem still occurs.

**Comment by W1zardK1ng** [comment]
> I suggest installing [Lawnchair 14 Beta 2](https://lawnchair.app/downloads/), the latest version of Lawnicons, and let us know if the problem still occurs.

Yes, the Beta2 version fixed this issue for me.
