### ISSUE TITLE
[BUG] Manually Changed Icons do not update colors/theme

### ISSUE THREAD

**Issue by SimplyAnotherAnon** [LawnchairLauncher/lawnicons#1241]
### About this discussion

Pretty Self-Explanatory, there a lot of apps which just dont have icons for them, so i select the closest-matching icon manually from Lawnicons, but when i change my wallpaper or theme, those manually-changed apps do not change theme, why?
Android 14 Beta 2, Pixel 6 Pro

![Screenshot_20230515-204445](https://github.com/LawnchairLauncher/lawnicons/assets/115472706/630d21d1-8fa1-479a-b02c-c41a3bb61ed1)

**Comment by GDNoob320** [comment]
Same problem but the app auto selects the icon for the app but not the color scheme.
![Screenshot_20230516-102901_Lawnchair](https://github.com/LawnchairLauncher/lawnicons/assets/89239362/a9e18a7d-d146-415c-be3c-efda9805be97)

**Comment by GDNoob320** [comment]
> Same problem but the app auto selects the icon for the app but not the color scheme. ![Screenshot_20230516-102901_Lawnchair](https://user-images.githubusercontent.com/89239362/238537554-a9e18a7d-d146-415c-be3c-efda9805be97.jpg)

It's seems to break on the latest update 2.1.0

**Comment by GDNoob320** [comment]
> > Same problem but the app auto selects the icon for the app but not the color scheme. ![Screenshot_20230516-102901_Lawnchair](https://user-images.githubusercontent.com/89239362/238537554-a9e18a7d-d146-415c-be3c-efda9805be97.jpg)
> 
> It's seems to break on the latest update 2.1.0

![Screenshot_20230516-104127_Lawnchair](https://github.com/LawnchairLauncher/lawnicons/assets/89239362/1bb31bee-8e88-43b2-9870-eea73b1dedb9)
Confirmed.

**Comment by SuperDragonXD** [comment]
See this comment for more information.

https://github.com/LawnchairLauncher/lawnicons/pull/1268#issuecomment-1566075967

Also the clock icon is a separate issue, will plan to fix that soon™.

**Comment by zeletrik** [comment]
Any news on this? 🙇

**Comment by PigeonCoding** [comment]
Hello so i found out that using the all repainter to force change the theme and then updating the icons by changing icon theme and then going back to lawnicons on lawnchair and switching tbe theme fixed my problem![Screenshot_2023-11-11-12-22-33-063_app.lawnchair.jpg](https://github.com/LawnchairLauncher/lawnicons/assets/77279028/43d53265-6b9e-46dd-94e6-247327776b75)

**Comment by x9136** [comment]
I suggest installing [Lawnchair 14 Beta 2](https://lawnchair.app/downloads/), the latest version of Lawnicons, and let us know if the problem still occurs.

**Comment by PigeonCoding** [comment]
this bug appears to be fixed I'm on lawnchair 14 beta 2 and have the latest lawnicons and the issue has disappeared
