### ISSUE TITLE
Discrepancy between themed and unthemed icons

### ISSUE THREAD

**Issue by thespeck** [LawnchairLauncher/lawnicons#1263]
### About this discussion

Some of the icons does not have themed version, like `com.coloros.alarmclock`. It does not get themed.

On the other hand, Phone (`com.android.contacts.DialtactsActivityAlias`) and Contacts (`com.android.contacts.PeopleActivitiAlias`) have same themed icon, but they have different icons when they are not themed.

![ThemedUnthemed](https://github.com/LawnchairLauncher/lawnicons/assets/67034266/c5e704bf-c718-4b3b-907c-c036e2a8ff75)

**Comment by x9136** [comment]
Is #1241 related?

I suggest installing [Lawnchair 14 Beta 2](https://lawnchair.app/downloads/), the latest version of Lawnicons, and let us know if the problem still occurs.

**Comment by thespeck** [comment]
I don't have access to that device anymore. So, unfortunately I cannot test it.
