### ISSUE TITLE
[DISCUSSION] Add generic alphabetical icons

### ISSUE THREAD

**Issue by lorrding** [LawnchairLauncher/lawnicons#1287]
### About this discussion

As far as I know, we don't have any generic letter icons.

It could be useful to have a set of generic icons that are not bound to any app but could be used as a way to temporarily cover one that is not yet supported or linked to apps that uses a letter.

The first thing that comes to my mind could be apps like `Google` that users could bind to `generic_G` until we have an actual icon for it (obviously we already have in this case).
Some apps also just have a letter for their icons. A great example is the [Numworks](https://github.com/numworks) app. Their app icon is just a big `N`, so instead of making a new icon with a name like `numworks.app` we could just link to the generic_N icon.

Think of theses like the generic `gallery`/`calculator`/`message`/`contact` icons we already have.

**Comment by everypizza1** [comment]
This would help with some Adobe apps.
![Screenshot_20230822-171507.jpg](https://github.com/LawnchairLauncher/lawnicons/assets/82726593/74616d83-86e2-446e-87c7-8968e6c79696)

**Comment by x9136** [comment]
@SuperDragonXD Say there are 26 alphabetical icons. What will they be linked to or organized in the overall appfilter.xml structure? A separate section with an empty package?

**Comment by SuperDragonXD** [comment]
Most of them *won't* be mapped in `appfilter.xml` itself (to prevent issues with launchers and dummy apps), but they could be added in a custom `generic_map.xml` with all the generic icons/apps:

```
generic_map.xml
```
```xml
...
  <item component="" drawable="generic_G" name="G" />
  <item component="" drawable="generic_G_lower" name="g" />
  <item component="" drawable="generic_camera" name="Camera" />
```

**Comment by x9136** [comment]
Half of the task [is done](https://www.figma.com/file/IoUXJrSEPTBhhsTkvnMsN2/Lawnicons-%E2%80%A2-Generic-alphabetical-icons?type=design&node-id=0%3A1&mode=design&t=JndLH8yOw6eAP2W4-1). You can take the icons as is or improve them, and then move on to implementation.

**Comment by x9136** [comment]
I added 26 letters of the alphabet, so I consider the task completed.

To simplify the installation of these icons, you need to refine the Lawnchair: https://github.com/LawnchairLauncher/lawnchair/issues/4880

**Comment by bilogic** [comment]
I can't seem to use these icons in Lawnchair 15
