### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [LawnchairLauncher/lawnicons#1300]
### About this discussion

Just a short heads-up/reminder to please **always** increase `versionCode` when making a new release:

    Binary files /web/ftp/repo/fdroid/repo/app.lawnchair.lawnicons_4.apk and /web/ftp/repo/fdroid/repo/app.lawnchair.lawnicons_2.2.0.apk differ

That means the previous and the current release both came with `versionCode: 4`. So those having the previous version installed won't receive any update notifications (and thus no updates) for the current one, as Android thinks there is no update (since `versionCode` did not change). Android uses this to tell which APK is newer.

Thanks in advance!

**Comment by SuperDragonXD** [comment]
Thanks for the reminder! Addressed in the latest release.

**Comment by IzzySoft** [comment]
Thanks!
