### ISSUE TITLE
[DISCUSSION] Not a request for Icon, but...

### ISSUE THREAD

**Issue by prpjzz** [LawnchairLauncher/lawnicons#1303]
### About this discussion

I have a problem like this: Wild Rift in our home country (Vietnam), name package: com.riotgames.league.wildriftvn is a localized application of the international version, and it is no different from the international version, so it is possible to share Icon with the international version. The name of the application is "LMHT: Tốc Chiến". Can you update the icon for this application?

**Comment by SiMah5** [comment]
yeah that's possible, i'll add it in my next PR and will notify you when its merged(added to the app).

**Comment by prpjzz** [comment]
Thank you bro, @SiMah5
