### ISSUE TITLE
中国软件图标有非常多的不适配

### ISSUE THREAD

**Issue by sujiuer5201314** [LawnchairLauncher/lawnicons#1307]
### About this discussion

中国有非常多的图标没有适配，是否有办法让启动器自己取色自动生成莫奈图标，哪怕没这么好看不然没有适配的软件有严重的割裂感

> There are a lot of icons in China that are not adapted. Is there a way to let the launcher automatically generate the Monet icon by picking its own color?

**Comment by TylerMS887** [comment]
Google translation (for those who don't understand Chinese):
> **About this discussion**<br><sup>There are a lot of icons in China that are not adapted. Is there a way to let the launcher automatically generate the Monet icon by picking its own color?</sup>

**Comment by SiMah5** [comment]
No lawnicons doesn't have this feature, you can use the [icon request form](https://forms.gle/Fx8vZAiWdW1Tyjo57) to request the apps that don't have icons yet. 

不，lawnicons没有此功能，您可以使用[图标请求表](https://forms.gle/Fx8vZAiWdW1Tyjo57)来请求还没有图标的应用程序。

**Comment by x9136** [comment]
Looks like the author of the issue has gotten an answer, so I suggest closing it.
