### ISSUE TITLE
Icon port request

### ISSUE THREAD

**Issue by wolf-yuan-6115** [LawnchairLauncher/lawnicons#1312]
### About this discussion

`com.lge.clock` is default (stock) clock app on LG, please port Google clock icon to it. Thanks!
![Screenshot_20230624-003910](https://github.com/LawnchairLauncher/lawnicons/assets/58245644/6cb14f3d-128e-4f7e-a7c6-ec784c11f40f)

**Comment by x9136** [comment]
@wolf-yuan-6115 Could you copy the entire name of the app component [via IconRequest app](https://github.com/Kaiserdragon2/IconRequest/releases) and past it in a comment?

https://github.com/LawnchairLauncher/lawnicons/assets/60105060/24639774-881d-4b06-9f2e-b1ace00fe1c6

**Comment by wolf-yuan-6115** [comment]
> @wolf-yuan-6115 Could you copy the entire package name [via IconRequest app](https://github.com/Kaiserdragon2/IconRequest/releases) and past it in a comment?
> 
> https://github.com/LawnchairLauncher/lawnicons/assets/60105060/24639774-881d-4b06-9f2e-b1ace00fe1c6

Sure!

```
<appfilter>

	<!-- Clock -->
	<item component="ComponentInfo{com.lge.clock/com.lge.clock.AlarmClockActivity}" drawable="clock"/>

</appfilter>
```

**Comment by x9136** [comment]
@wolf-yuan-6115 you can check it [in the Debug version](https://github.com/LawnchairLauncher/lawnicons/actions/runs/5554486822).
