### ISSUE TITLE
[DISCUSSION] Home Assistant icon is too crowded

### ISSUE THREAD

**Issue by KTibow** [LawnchairLauncher/lawnicons#1313]
### About this discussion

The current HA icon is way too crowded and looks awful:
![image](https://github.com/LawnchairLauncher/lawnicons/assets/10727862/d39fca1c-daef-4dcc-b018-8d1176db179c)
While, yes, the official icon is complex like that, it can get away with it because its stroke width is thin. Instead Lawnicons should use the simplified icon:
https://github.com/home-assistant/assets/blob/9b782fe562cbd4e6139f9be17d8e7befafa5f945/logo/logo-small.svg

**Comment by x9136** [comment]
I agree. I will offer another svg in an upcoming PR.

**Comment by x9136** [comment]
✔️ https://github.com/LawnchairLauncher/lawnicons/commit/bbccb03c47e711f56ba08c906b8e855c33cabb70
