### ISSUE TITLE
Icon not included in latest Debug Artifact

### ISSUE THREAD

**Issue by Sir-Photch** [LawnchairLauncher/lawnicons#1324]
I've noticed that the icon I've added in #1315 is not present in the latest Debug artifact. Is there any specific reason to this? It neither links to the app-icon neither is it searchable in the lawnicon-app itself.

**Comment by lorrding** [comment]
There's no closing curly bracket in the value of the *component* attribut on `appfilter.xml`.
https://github.com/LawnchairLauncher/lawnicons/blob/2c7a22cd3aa293173d174121919d431afb6e6683/app/assets/appfilter.xml#L1034

**Comment by Sir-Photch** [comment]
Good catch. I'll let myself out 🚶🏼‍♂️
