### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Fr3uds** [LawnchairLauncher/lawnicons#1363]
### About this discussion

I share the fil taken by icon request app, ty soo much for the fantastic work
[IconRequest_25072023_235313.zip](https://github.com/LawnchairLauncher/lawnicons/files/12165964/IconRequest_25072023_235313.zip)

**Comment by Chefski** [comment]
I'll be closing this issue as icon requests should be sent to the [form](https://docs.google.com/forms/d/e/1FAIpQLSeiRgR6nTnS0AdhnZn4ypR37yjWe3c3z_YmjqiL-O8f7oqaTw/viewform). If you haven't already, send the requests there :)
