### ISSUE TITLE
Improve Genshin Impact icon

### ISSUE THREAD

**Issue by everypizza1** [LawnchairLauncher/lawnicons#1369]
### About this discussion

The Genshin Impact icon looks nothing like the official one. Not much of a problem, just slightly annoying.

**Comment by x9136** [comment]
@everypizza1 In your opinion, what icon would be recognizable for Genshin Impact other than the characters?

**Comment by everypizza1** [comment]
I re-read the guidelines and realized that the official icon is too complex, so the current one is fine.
