### ISSUE TITLE
Catogram icon support request

### ISSUE THREAD

**Issue by mintyleaf** [LawnchairLauncher/lawnicons#14]
ua.itaysonlab.messenger

https://github.com/catogram/catogram
https://t.me/catogram
https://iconpusher.com/device/c70cab805f78506a/ua.itaysonlab.messenger

**Comment by rodrigoswz** [comment]
Unfortunately Catogram announced that it has been discontinued
https://t.me/catogram/387

**Comment by hardeik** [comment]
@mintyleaf I think this issue should be closed given that Catogram icon has been added.
