### ISSUE TITLE
InnerTune and AnonAddy icons are outdated

### ISSUE THREAD

**Issue by BabyBenefactor** [LawnchairLauncher/lawnicons#1409]
### About this discussion

InnerTune (https://github.com/z-huang/InnerTune) (com.zionhuang.music) has been updated to a new icon since 0.5.0 release. AnonAddy also has had a new icon becouse of the rebrand to Addy.io (https://gitlab.com/Stjin/anonaddy-android) (host.stjin.anonaddy) 

These should be updated but I do not have the skills to create them on my own. Thanks for considering this

**Comment by SiMah5** [comment]
thanks for the info! i will make the new icons and do a PR in one or two days.

**Comment by BabyBenefactor** [comment]
Cheers, thanks.

**Comment by BabyBenefactor** [comment]
Thanks for updating! 👍
