### ISSUE TITLE
Via Browser icon request

### ISSUE THREAD

**Issue by 54m33r4** [LawnchairLauncher/lawnicons#15]
I know that chrome is more important but at the same time... Via is one of the best geek browsers out there so many people use. Please theme it's icon too in a recent build🤍
<img width="256" alt="Via" src="https://user-images.githubusercontent.com/68902530/140588853-218b7f53-5c9c-4a2d-9b10-95f44f8046e2.png">

Thank you!❤️

**Comment by patrykmichalik** [comment]
Hello! I’ve just added an icon for Via Browser.
