### ISSUE TITLE
[DISCUSSION] Script to get the wishlisted and actually missing apps

### ISSUE THREAD

**Issue by ElbertCode** [LawnchairLauncher/lawnicons#1518]
### About this discussion

The list generated via the icon request form currently is a total mess containing different naming schemes, duplicates and apps that are already implemented. So I wrote a little Python which fetches the wishlist and brings some order into it.

[get_missing_apps.py.txt](https://github.com/LawnchairLauncher/lawnicons/files/12961939/get_missing_apps.py.txt) (it is actually a python script, but GitHub didn't let me upload it so you have to remove ".txt" from the file name)

I couldn't find something similar, the "summary of the requests" doesn't seem to work that well to me. I hope this script can help and this is the right place to post it.

**Comment by x9136** [comment]
I don't know how to use it, but could you show an example of the result?

Even though there is a lot of unnecessary stuff [in the popular requests table](https://docs.google.com/spreadsheets/d/10_o0DjhAGfP8ToDDNQ8M7eCZKtbzXLhIvxuF1XZEql0/edit#gid=327531090&range=C2), it still remains useful and is updated automatically.

**Comment by ElbertCode** [comment]
It's a python script so to run it, you would just rename the file to `get_missing_apps.py` and then run `python get_missing_apps.py` in a terminal (you need the packages `re` and `requests`). The script then creates a file called `missing_apps.txt`.

Here's what I got from running this script:
[missing_apps.txt](https://github.com/LawnchairLauncher/lawnicons/files/12997221/missing_apps.txt)

**Comment by x9136** [comment]
> Here's what I got from running this script:
[missing_apps.txt](https://github.com/LawnchairLauncher/lawnicons/files/12997221/missing_apps.txt)

If I understand correctly, your script allows you to clean the raw data. It would be useful in conjunction with a list of popular requests. Right now the list of popular requests is a bit irrelevant because of the raw data.

If @KTibow has time, he will tell more precisely whether this script can be used when generating a list of popular requests.

**Comment by ElbertCode** [comment]
[get_missing_apps.py.txt](https://github.com/LawnchairLauncher/lawnicons/files/12998986/get_missing_apps.py.txt)

I've done some tweaking to the script and added a counter as well, so the output format is now a CSV. Now from a first look, the output list looks quite similar to the one from the Google Sheet, with the difference that it really only contains reverse domain names.

An example of the output now is:
[missing_apps.csv](https://github.com/LawnchairLauncher/lawnicons/files/12998991/missing_apps.csv)

**Comment by x9136** [comment]
>I've done some tweaking to the script and added a counter as well

Yep, the result is similar, but a little different.

I should emphasize that the table has a significant advantage — as soon as a PR with ready icons is merged with the repository, the list of popular requests updates itself. That's why I say above that it's best to apply a script that cleans up the raw data in the table itself.

**Comment by ElbertCode** [comment]
> I should emphasize that the table has a significant advantage — as soon as a PR with ready icons is merged with the repository, the list of popular requests updates itself. That's why I say above that it's best to apply a script that cleans up the raw data in the table itself.

Of course, That is also the way I intended the script to be implemented - if at all. I just don't know how to do it with Google Sheets, otherwise I would have done it that way already.

**Comment by x9136** [comment]
@ElbertCode

@KTibow took the time to update [the list of popular requests](https://docs.google.com/spreadsheets/d/10_o0DjhAGfP8ToDDNQ8M7eCZKtbzXLhIvxuF1XZEql0/edit#gid=327531090&range=C2), so it now cleans the raw data before sorting, although it counts differently than your script.

I don't know the code, but I'll explain the difference with an example if you're interested. In `missing_apps.csv` you have `org.supertuxkart.stk, 8`, but if you look at the list of popular requests, it says `org.supertuxkart.stk 6`. I think 6 is correct — if you search the raw data, there are 6 entries.
![Screenshot 2023-10-18 at 17 57 14](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/15b39401-5116-421d-b07a-e0b9cbba389b)
