### ISSUE TITLE
[DISCUSSION] Improve style support when using icontool.py

### ISSUE THREAD

**Issue by x9136** [LawnchairLauncher/lawnicons#1522]
I have a guess that the re-sorting when linking (and possibly when adding) is wrong. As a result, I have to fix appfilter.xml manually to pass the style test.

I may be wrong, so I will describe the case.
1. Before creating [the PR](https://github.com/LawnchairLauncher/lawnicons/pull/1517), I cloned the repository on my computer and did not change applfilter.xml. So we'll assume everything was fine.
2. I made a couple of commits that didn't touch applfilter.xml.
3. I hand-corrected only the names in a few components. That is, the position of the strings didn't change, only the content.
4. I ran the following command in terminal to link the unused icons and their components:
```
python3 icontool.py link xvii com.twoeightnine.root.xvii/com.twoeightnine.root.xvii.login.LoginActivity "xvii"
python3 icontool.py link securego_plus de.fiduciagad.securego.wl/de.fiduciagad.securego.MainActivity "SecureGo plus"
python3 icontool.py link movie_lab com.movielab.mobile/com.movielab.MainActivity "MovieLab"
python3 icontool.py link erste_hilfe com.cube.gdpc.che/com.cube.gdpc.fa.BootActivity "First Aid"
python3 icontool.py link istanbulkart com.belbim.istanbulkart/com.belbim.istanbulkart.MainActivity "İstanbulkart"
python3 icontool.py link tricount com.tribab.tricount.android/com.tribab.tricount.android.view.activity.SplashActivity "Tricount"
python3 icontool.py link samsung_health_monitor com.samsung.android.shealthmonitor/com.samsung.android.shealthmonitor.ui.activity.MainActivity "Samsung Health Monitor"
python3 icontool.py link z1 app.z1.mobile/app.z1.mobile.MainActivity "Z1"
python3 icontool.py link gramotnee com.gramotnee.orpho/com.gramotnee.orpho.view.screen.main.MainActivity "Orthography"
python3 icontool.py link camera_date_folders de.kromke.andreas.cameradatefolders/de.kromke.andreas.cameradatefolders.MainActivity "Camera Date Folders"
python3 icontool.py link tinkoff_work ru.tinkoff.twork/ru.tinkoff.twork.activity.HostActivity "Tinkoff Work"
python3 icontool.py link animiru xyz.Quickdev.Animiru.mi/eu.kanade.tachiyomi.ui.main.MainActivity "Animiru"
python3 icontool.py link penta com.getpenta.app/com.getpenta.app.MainActivity "Penta"
python3 icontool.py link russian_language_quiz com.yugyd.russianlanguagequiz/com.yugyd.quiz.main.MainActivity "Russian Language Quiz"
python3 icontool.py link mi_freeform com.sunshine.freeform/com.sunshine.freeform.ui.splash.SplashActivity "Mi Freeform"
```

6. I made a commit that [did not pass the style test](https://github.com/LawnchairLauncher/lawnicons/actions/runs/6574209233/job/17858793168).
7. [I corrected the offset of two lines](https://github.com/LawnchairLauncher/lawnicons/pull/1517/commits/96f8b53c526233aaacf175a80fe7826d33da534f) and passed the style test.

I propose to make icontool.py move the strings correctly in such a case.

**Comment by SuperDragonXD** [comment]
Apologies for the delay. I can't seem to replicate this issue. Could you provide another example regarding this?

**Comment by x9136** [comment]
> Could you provide another example regarding this?

I don't have much to add. Same thing happened [here in 1 commit](https://github.com/LawnchairLauncher/lawnicons/pull/1528).

```
...
python3 icontool.py add /Users/otttis/Desktop/export/beautyplus com.commsource.beautyplus/com.commsource.beautyplus.start.StartUpAdvertActivity "BeautyPlus"
...
```
I had a list of such commands. I ran it through Terminal and only discovered that the style was incorrect when I created the PR.

Since you didn't find anything after a detailed explanation, there is probably nothing wrong with icontool.py. The string offset could have appeared earlier and in some other way. I just don't realize how, because I was working with appfilter.xml through Terminal.

If nothing is found, you can close the issue because it happened 3 times in 30+ PRs (one time I waited for it and fixed appfilter.xml before committing), not all the time.

**Comment by x9136** [comment]
The issue went away without any code modifications.
