### ISSUE TITLE
[DISCUSSION] Create an iOS lawnchair icon pack

### ISSUE THREAD

**Issue by peterge1998** [LawnchairLauncher/lawnicons#1545]
### About this discussion

Hey guys, I didn’t contribute to lawnicons in a while because I had some RL stuff going on. Now I am back - using an iPhone 15 Pro Max 😳 instead of a Pixel 7 with lawnchair & lawnicons. 

BUT: it’s possible to use an icon pack in iOS through shortcuts too!
See [this mkbhd video](https://youtu.be/cH66LWWluVE?si=_5R8JGl0G741i4s8?t=6m8s) where he showcases the [tr.af icon pack](https://tr.af/icons).

I would love to create this with lawnicons too (because I prefer to use my own foss icons 😉). As far as I understand, iOS icon packs are basically just zip folders with PNG files. This should be fairly easy, but I haven’t looked into this yet. I would love to create the icon shape just similar like it’s on android. Add for the colour my suggestion would be to stick to white only. The problem is, that I needed some help creating these PNG files. 

Would you do me, currently contributor # 9 when counting commits, this favour and help me with this?
Thanks a lot! <3

![IMG_0037](https://github.com/LawnchairLauncher/lawnicons/assets/47355238/4d6c0a79-913e-4a9c-a86e-dd8954d0566f)

**Comment by x9136** [comment]
> This should be fairly easy.

Hello. I suggest you first figure out how you are going to make the icon set, how it will be stored and how you will be able to share it.

Something tells me that this task will take you at least 50 hours, even if you convert all the icons from the Lawnicons set to PNG at once. And other iOS users won't be able to apply your set as easily as Android users can. Not to mention figuring out what apps are on both systems.

Good luck, either way.

**Comment by peterge1998** [comment]
After researching more on this topic, the only possible way to do custom icons on iOS nowadays seems to be through shortcuts, since [icon themer](https://routinehub.co/shortcut/6565/) is dead:
https://www.xda-developers.com/how-to-set-up-custom-icon-packs-on-iphone/

So I will close this :(
Hopefully Apple does make it possible again without too much manual work…

**Comment by peterge1998** [comment]
![30643058-594F-42B7-9BA4-60E5242B196E_1_101_o](https://github.com/LawnchairLauncher/lawnicons/assets/47355238/14b197c0-f2aa-48e6-b71c-107694ca3f32)

Done :)
