### ISSUE TITLE
Google Chat icon outdated 

### ISSUE THREAD

**Issue by ThatOneCalculator** [LawnchairLauncher/lawnicons#1662]
### About this discussion

Google recently updated the Google Chat icon. Frankly, I'm not a fan of the new icon, but it should be changed regardless. 

New icon:
![Screenshot_20231212-130939~2](https://github.com/LawnchairLauncher/lawnicons/assets/44733677/de051f3d-0380-4e31-8f46-c0fc4e41b7dd)

Current Lawnicon:
![Screenshot_20231212-130935~2](https://github.com/LawnchairLauncher/lawnicons/assets/44733677/2193d9f5-b393-4d00-80d1-ba3619c5a6bd)

**Comment by x9136** [comment]
@ThatOneCalculator ✔️
