### ISSUE TITLE
Themed icon is on the list but not applying

### ISSUE THREAD

**Issue by tahmid8464** [LawnchairLauncher/lawnicons#169]
Nekogram v8.2.7.1
tw.nekomimi.nekogram

**Comment by arun54321** [comment]
It's not on the list.

**Comment by tahmid8464** [comment]
> It's not on the list.

![Screenshot_20211203-033240_Lawnicons](https://user-images.githubusercontent.com/82872624/144506584-75e059d5-8442-4c12-84bd-6f8b322184c8.png)
See it is on the list

**Comment by arun54321** [comment]
It's nekogram x.
