### ISSUE TITLE
Improving search instead of formally creating categories

### ISSUE THREAD

**Issue by x9136** [LawnchairLauncher/lawnicons#1715]
I think that categorizing icons is a useless solution. At least, I don't see significant cases when it's useful. I realize that it's quite easy to make and maintain categories by letters, but the main issue of large lists is a search. In huge lists, it's easier to search than to navigate through the categories, even if they will be perfect.

So I would suggest improving the search. Foremost, I suggest writing a section on naming in the Lawnicons guide and sticking to it.

It would be easier to find icons if we considered the following rules:

### Name of the drawable
Should be in English, and preferably in a few words if the original also has a few words. Should repeat the name of the app if possible.

Wrong
```
<item component="..." drawable="meinvodafone" name="My Vodafone • MeinVodafone" />
```
Correct
```
<item component="..." drawable="my_vodafone" name="My Vodafone • MeinVodafone" />
```
### Name of the app
Should be the same as in Google Play, F-Droid or the official name. If the official name is too long, it's acceptable to remove the second part of the name without loss of recognition.

Wrong • Google Play name: "My Vodafone — Stay on top of your plan"
```
<item component="..." drawable="my_vodafone" name="My Vodafone — Stay on top of your plan or prepaid service" />
```
Correct • Edited name: "My Vodafone"
```
<item component="..." drawable="my_vodafone" name="My Vodafone" />
```

If the app name doesn't have an English localization, then you need to properly translate the name into English and add it after the original name via `•`. _I suggest the rarer symbol because `/` is occasionally found in application names._

Wrong
```
<item component="..." drawable="niconico" name="ライブ配信 ニコニコ生放送" />
```
Correct
```
<item component="..." drawable="niconico" name="ニコニコ • Niconico" />
```

If the app name is localized, then the first name should be the one most commonly spoken by the people who will be searching for the icon (if in doubt, in English).

Wrong
```
<item component="..." drawable="my_vodafone" name="MeinVodafone" />
```
Correct
```
<item component="..." drawable="my_vodafone" name="My Vodafone • MeinVodafone" />
```

--
**You are welcome to join the discussion.** @Chefski

**Comment by Chefski** [comment]
I guess name of drawable could be in English. Name of apps could be shortened too but there's very little cases of it. Symbol needs to stay something simple so that it can be found on the keyboard.

**Comment by x9136** [comment]
> Symbol needs to stay something simple so that it can be found on the keyboard.

Good point. I have an extended layout, so I can enter "•" and other rare characters from the keyboard, but hardly anyone will install the same layout.

If we leave the slash and, say, we need to display one name separately as the main name and the others as additional ones or hide the symbol for the sake of cleanliness, then apps like "SMS Import / Export" or "SD Maid 2/SE" will be misspelled. Then I suggest using "~": My Vodafone ~ MeinVodafone.
