### ISSUE TITLE
[BUG] Wrong icon for LineageOS (and other OSs) dialer

### ISSUE THREAD

**Issue by thatAkiraFox** [LawnchairLauncher/lawnicons#1728]
### About this discussion

In Lawnicons version `2.5.0 Dev #4130` the Contacts app icon is linked to the LineageOS dialer (`com.android.dialer`), thus showing the wrong icon for the dialer.

![Screenshot_20240104-172750_Lawnchair (Debug)-01](https://github.com/LawnchairLauncher/lawnicons/assets/49398464/57e2bd2c-b06e-4daf-84c3-935bb23f81bf)

**Comment by x9136** [comment]
Hey! Many apps have the same package as this icon (com.android.dialer), so we need to specify the activity.

Could you please share the package with activity for this app? If you don't know how, [there are options](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#iconrequest-app).

**Comment by thatAkiraFox** [comment]
```
<appfilter>

	<!-- Phone -->
	<item component="ComponentInfo{com.android.dialer/com.android.dialer.main.impl.MainActivity}" drawable="phone"/>

</appfilter>
```

Is this correct?

**Comment by x9136** [comment]
As far as I can see, [the icon is linked correctly](https://github.com/LawnchairLauncher/lawnicons/blob/7233bcb1c0098b5dd146d85ec426bca8a1110226/app/assets/appfilter.xml#L4765C3-L4765C130).

@SuperDragonXD Could you see if you get a chance. Is this issue related to the one we've been talking about recently? Any ideas on how to fix it?

**Comment by SuperDragonXD** [comment]
I guess it's semi-related. The best thing to do is to test all the activites of the app and see which ones are correctly mapped to the right drawable.

Could you check what Lawnchair shows for that themed icon by enabling the `show_component_name` flag (in Debug Menu)? (Also sometimes the phone activity is actually in `com.android.contacts`)

**Comment by x9136** [comment]
> Could you check what Lawnchair shows for that themed icon by enabling the `show_component_name` flag (in Debug Menu)?

Same activity.
![DebugIcon](https://github.com/LawnchairLauncher/lawnicons/assets/60105060/03f492fa-c4d3-4fe2-a97f-610909fe8ecf)

**Comment by searinminecraft** [comment]
lineageos 19.1, same issue here. but like mentioned above on dev build it shows correct icon


[Screenshot_20240112-221318_Lawnchair.png](https://github.com/LawnchairLauncher/lawnicons/assets/114207889/6eb0d48b-6458-44cc-8269-8e8bd0887ffb)

**Comment by x9136** [comment]
Try [Lawnchair 14 Beta 2](https://lawnchair.app/downloads/). If the error persists, share the package with the activity here.

**Comment by thatAkiraFox** [comment]
Yup, still happening here on 14 Beta

[IconRequest_14042024_105542.zip](https://github.com/LawnchairLauncher/lawnicons/files/14970031/IconRequest_14042024_105542.zip)

**Comment by x9136** [comment]
> Yup, still happening here on 14 Beta

Hmm, but it should work. Then I suggest **installing the icon manually**. It works better in L14.

As for the reasons.
Hypothesis 0. The cache has not been updated.
Hypothesis 1. Dialer and Contacts have the same activity in LineageOS and GrahpeneOS.
Hypothesis 2. The activity shown by IconRequest and other apps is incorrect. The real one is different.
Hypothesis 3. LineageOS and GrapheneOS have some features that are not taken into account in Lawnchair.

**Comment by thatAkiraFox** [comment]
>  installing the icon manually

What do you mean?

> Hypothesis 0. The cache has not been updated.

My 14 beta install is clean, no backups restored either.

> Hypothesis 1. Dialer and Contacts have the same activity in LineageOS and GrahpeneOS.

Different activities, at least here in LineageOS:
```
<appfilter>

	<!-- Contacts -->
	<item component="ComponentInfo{com.android.contacts/com.android.contacts.activities.PeopleActivity}" drawable="contacts"/>

	<!-- Phone -->
	<item component="ComponentInfo{com.android.dialer/com.android.dialer.main.impl.MainActivity}" drawable="phone"/>

</appfilter>
```

> Hypothesis 2. The activity shown by IconRequest and other apps is incorrect. The real one is different.

Would an app like activity launcher help?

> Hypothesis 3. LineageOS and GrapheneOS have some features that are not taken into account in Lawnchair.

Well, I hope not.

**Comment by x9136** [comment]
> What do you mean?

Long press the Phone icon → Customize → Tap on the icon → Choose a new one

> Would an app like activity launcher help?

Shortcut Maker would be better suited (I guess). Can you share screenshots of Phone and Contact activities?
https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker

**Comment by thatAkiraFox** [comment]
> Long press the Phone icon → Customize → Tap on the icon → Choose a new one

That doesn't work, I've reported the issue.

> Can you share screenshots of Phone and Contact activities?

![Screenshot_20240414-120000_Shortcut Maker](https://github.com/LawnchairLauncher/lawnicons/assets/49398464/c9f96e2d-4444-40dc-86b9-453b866a6e10)
![Screenshot_20240414-115941_Shortcut Maker (1)-01](https://github.com/LawnchairLauncher/lawnicons/assets/49398464/e60b4d75-7c0d-4a4f-a602-e21edff3e88b)

**Comment by x9136** [comment]
> That doesn't work, I've reported the issue.

This argues in favor of the OS having some features that are not addressed in L14. :/

**Comment by thatAkiraFox** [comment]
> This argues in favor of the OS having some features that are not addressed in L14. :/

Applying Lawnicons to both the home screen and the drawer works just fine, so probably it's a Lawnchair issue after all?

**Comment by x9136** [comment]
> so probably it's a Lawnchair issue after all?

Most likely.

**Comment by thatAkiraFox** [comment]
> Most likely. Works only in "Home Screen & App drawer" mode, right?

I meant, when I apply Lawnicons in both home screen and drawer mode the phone icon is the right one, while in home screen only mode the wrong icon gets applied (the contacts icon)

**Comment by x9136** [comment]
Since the issue has been resolved or a workaround has been found for most, I close it. The issue about the remaining bug is open in the Lawnchair repository. https://github.com/LawnchairLauncher/lawnchair/issues/4281

**Comment by mengxiabing** [comment]
![image](https://github.com/user-attachments/assets/7f3e3929-37b8-4aca-8ed7-1411b06d6ac9)
