### ISSUE TITLE
Sort via icontool.py breaks appfilter.xml style

### ISSUE THREAD

**Issue by x9136** [LawnchairLauncher/lawnicons#1732]
[Unsorted appfilter.xml](https://github.com/LawnchairLauncher/lawnicons/pull/1731/commits/cc5e847a11464bbc996088d44b4f3b70e7a9aeaa#diff-78a61c73b85c0c3925b77023f7eb3e58598e746095876a601b21c72023c9a846)
↓
```
python3 ./icontool.py sort
```
↓
[Sorted appfilter.xml](https://github.com/LawnchairLauncher/lawnicons/pull/1731/commits/07a599057d854281324e2375d52ecda6ae90e2dc)

It's unclear why it's moving calendars and make copies.

UPD: After fixing the issue, remove the warning from the guides. #2019

**Comment by x9136** [comment]
#1738 also had random automatic offsets that are not clear what they depend on.

**Comment by SuperDragonXD** [comment]
Fixed in https://github.com/LawnchairLauncher/lawnicons/commit/62fdfb88c1934e852740b79f8673be88d4c715d5
