### ISSUE TITLE
Phone Icon is wrong

### ISSUE THREAD

**Issue by heschy2** [LawnchairLauncher/lawnicons#1737]
### About this discussion

The contacts app (com.android.contacts) has the Google Contacts icon, wich is weird but I can live with it. But the Telephone (com.android.dialer) also gets the Google Contacts icon, wich is obviously wrong.

**Comment by x9136** [comment]
Hey! If your dialer is different from what is described in #1728, could you please do the following?

1. Type `/lawnchairdebug` in all app search.
2. Open Lawnchair settings.
3. Tap the wrench at the top.
4. Enable `show_components_names`.
5. Long press the dialer icon and tap Edit.
6. Take a screenshot and upload it here.

**Comment by heschy2** [comment]
Oh I am sorry I didn't see this issue. Yes I am (most likely) using the same App as in that Issue (Lineage Dialer) because my OS (/e/) is based on Li eage and just unifies the (in-app) design, so it should technically apear as the same app to lawnchair. This is a duplicate of the issue you mentioned, i am sorry for that.
