### ISSUE TITLE
icon request 

### ISSUE THREAD

**Issue by UjjwalGupta007** [LawnchairLauncher/lawnicons#1769]
### About this discussion

Anilab (not on playstore, https://anilab.to/)

hubble (https://play.google.com/store/apps/details?id=money.myhubble&hl=en_IN&gl=US)

GyFTR (https://play.google.com/store/apps/details?id=com.gyftr&hl=en_IN&gl=US)

JustWatch (https://play.google.com/store/apps/details?id=com.justwatch.justwatch&hl=en&gl=US)

Pinterest Lite (https://play.google.com/store/apps/details?id=com.pinterest.twa&hl=en&gl=US)

Snipd (https://play.google.com/store/apps/details?id=ai.topicfinder.podcastdiscovery&hl=en&gl=US)

Vanced Manager

**Comment by x9136** [comment]
Why did you ignore the point about requesting icons when creating the issue?
