### ISSUE TITLE
Twitter 9.98  is using the X icon.

### ISSUE THREAD

**Issue by Gravarty** [LawnchairLauncher/lawnicons#1791]
### About this discussion

I never updated Twitter past 9.98 to work around the X changes, but unfortunately Lawnicons uses the X icon. I see that the Twitter icon is still included in the icon pack, but it's not possible to change a single icon just for the homescreen.
![Screenshot_20240128_123632_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnicons/assets/16298668/b9b7dd15-4cb0-49ed-9236-52bccf7eb2d2)

**Comment by x9136** [comment]
So I can only suggest installing, where on the main Twitter is still the old icon. So right now I can only suggest installing [Lawnicons 2.3.0](https://github.com/LawnchairLauncher/lawnicons/releases/tag/v2.3.0), where the main Twitter still has the old icons. But the old version is probably missing some other icons.

**Comment by Gravarty** [comment]
> As far as I can see, if an app has an icon in Lawnicons, it can't be changed.
> 
> So right now I can only suggest installing [Lawnicons 2.3.0](https://github.com/LawnchairLauncher/lawnicons/releases/tag/v2.3.0), where the main Twitter still has the old icon. But the old version is probably missing some other icons.

Okay, yeah it has a lot of missing icons but so far i only use it for the home screen, so it's not that bad. But it would be nice to built in a feature to change some of these icons without touching the app drawer icons, there a lot of great alternatives included in Lawnicons.

**Comment by x9136** [comment]
Now you can install [Lawnchair 14 Beta 2](https://lawnchair.app/downloads/) and change the new Twitter icon to [the Twitter Lite icon](https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs/twitter_lite.svg).

Long tap on X → Customize → Tap on the icon → Pick icon from Lawnicons → Search for "Twitter" → Select the Twitter Lite icon
