### ISSUE TITLE
revert back Moshidon Icon

### ISSUE THREAD

**Issue by Rorschach1010** [LawnchairLauncher/lawnicons#1792]
### About this discussion

For some reason the Moshidon icon lost the o some months ago. As it is now, it not only looks strange, the official icon also has that o.

https://github.com/LawnchairLauncher/lawnicons/commits/4dc40f05567b745cc3f2513aa19bd2088ab1065b/svgs/moshidon.svg
https://github.com/LawnchairLauncher/lawnicons/blob/1b77ba7a9882b0a3a32636e12295efb760841a02/svgs/moshidon.svg
https://github.com/LawnchairLauncher/lawnicons/blob/dfa3ab03377167dbaa397e59a014897934470c72/svgs/moshidon.svg

Not sure if this is the proper way to request this but since this isn't an icon request, this is the only way I found to request changes/optimizations.

**Comment by x9136** [comment]
When optimizing, I didn't notice that part of the icon was missing. Thanks, I got it back.

[Debug APK](https://github.com/LawnchairLauncher/lawnicons/actions/runs/7685734666)

**Comment by Rorschach1010** [comment]
wow, thanks a bunch for the really quick fix. I can't test it right now since the rom I use has lawnicons inbuilt as a system app so I have to wait for it to get properly released. In any way, big thanks for the really quick response and fix.
