### ISSUE TITLE
Icon request: Tidal Music

### ISSUE THREAD

**Issue by Futur3Sn0w** [LawnchairLauncher/lawnicons#192]
**Tidal Music**
com.aspiro.tidal
https://play.google.com/store/apps/details?id=com.aspiro.tidal

**Comment by arun54321** [comment]
Tidal is included now. https://github.com/LawnchairLauncher/lawnicons/commit/8169192e491c9bb4339d57a07ba9696ad948f812

**Comment by Futur3Sn0w** [comment]
Perfect, thank you; it looks great!

**Comment by arun54321** [comment]
I didn't add. I'm just informing.
