### ISSUE TITLE
Allow changing icons for apps with themed icons

### ISSUE THREAD

**Issue by x9136** [LawnchairLauncher/lawnicons#1967]
### About this discussion

As mentioned in #1791, you cannot change the icon that is assigned automatically. I suggest adding this feature to fix incorrect links right away, rather than waiting for a fix from the devs.

This is especially true for Lawnchair 12.1, because there the icon assignment process does not take into account activities, so even correcting the link will not fix the icon when different apps have the same package.

**Comment by krzemyczek** [comment]
That would be nice for choosing similar icon for app that is not included. In my case some open source camera, i could just select otger camera icon. 
(thanks for the awesome app, btw :D)

**Comment by x9136** [comment]
> That would be nice for choosing similar icon for app that is not included too.

What prevents you from doing this now?

**Comment by krzemyczek** [comment]
> What prevents you from doing this now?
but can I? your reply suggest but yes, I didn't check it deeper

**Comment by x9136** [comment]
> but can I? your reply suggest that yes, but I didn't check it deeper

If you are using the latest version of Lawnchair: Long press on an app icon → "Customize" → Tap on the icon in the opened sheet. In the old version, it's about the same. I don't know how in other launchers.

**Comment by krzemyczek** [comment]
oh my god. I didn't try it. Thanks man! It's gonna change me a lot of things on my phone xD

**Comment by x9136** [comment]
Refers to Lawnchair rather than Lawnicons.
