### ISSUE TITLE
icon name  font text color not same

### ISSUE THREAD

**Issue by Ansarmughal99** [LawnchairLauncher/lawnicons#2041]
### About this discussion

The icon name font color is not same on Home screen And App Drawer
![IMG_20240427_220558](https://github.com/LawnchairLauncher/lawnicons/assets/74392407/9f74cd9a-aa45-4a3e-865e-953f811f7828)
![Screenshot_2024-04-27-22-06-11-57_67d7f8591eff9881972c1169b8bca2d8_1](https://github.com/LawnchairLauncher/lawnicons/assets/74392407/b96fd7f5-3d9b-48b3-8267-60a3cea3cec6)

**Comment by x9136** [comment]
This issue applies to [Lawnchair](https://github.com/LawnchairLauncher/lawnchair) or the launcher you are using.
