### ISSUE TITLE
Checklist for self-review

### ISSUE THREAD

**Issue by x9136** [LawnchairLauncher/lawnicons#2070]
### About this discussion

I want to change #1318 a little bit so that it is useful, but at the same time easy to implement.

Due to the fact that difficulties with taking into account the Lawnicons guidelines occur after several PRs, I suggest making a checklist for self-review. This checklist should be sent via **github-actions** as the first comment on all PRs that have icons.

Such a checklist can be useful for both beginners and contributors who rarely add icons (to remind them of the main points of the guidelines). It will also save some time for reviewers, because they will be less likely to repeat themselves.

**Suggestion**

```
Hey! Thanks for the contribution. While there is no reviewer, you can do a self-review. This will help to fix the reasons why the icons may not be suitable for Lawnicons. 

### Canvas and sizes [→](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#canvas--sizes)
1. Canvas: `192×192px`.
2. Non-square icons: the long side of the icons should be `160px`.
3. Square icons: `154×154px`.

### Color, stroke width and rounding [→](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#foundation)
1. Color: black `#000`.
2. No fill. Base stroke width: `12px`. `14px`, `10px`, `8px` — depending on the shape of the icons. `6px` — for fine details.
3. Rounded ends and joins. 90° corners are rounded by `6-32px`.

### Naming [→](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#naming)
1. Names should match the official ones and contain no additional text.
2. If the original name is not in English, then add a localized (or transliterated) one to it using `~~`.
Example: `フールー ~~ Hulu`.
3. The names of the drawables should repeat the names of the apps if nothing prevents it.

### Quality [→](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#details)
1. Icons should be easily recognizable.
2. Align icons to [the visual center](https://www.google.com/search?sca_esv=1fcec3f5e0b15e20&q=what+is+visual+center+of+an+icon&tbm=isch&source=lnms).
3. No blackness. Reduce the stroke width or simplify the icons so that there are no noticeable black spots.
4. Avoid close distances between strokes. The icons on the phone screen will be smaller, so the small distances between the strokes will stick together.
5. Avoid drastic changes in stroke widths. When the strokes next to each other differ in width by 4px or more, the icon will look sloppy.

```

**Comment by Hamster45105** [comment]
Hi @x9136 I think this is a good idea and as such, have made a GitHub action that does this.

How the action works:

When a PR is opened that involves files ending in `.svg`, `github-actions` will leave a comment. This comment can be found and edited in `.github/icon_checklist.md`

Here is an example of it running on a PR: https://github.com/Hamster45105/lawnicons/pull/4
Workflow file: https://github.com/Hamster45105/lawnicons/actions/runs/8957475337/workflow

If you could provide me with the checklist I would be happy to open a PR.

**Comment by Hamster45105** [comment]
Hi @x9136 I think this is a good idea and as such, have opened a PR with an action that does this task.

See https://github.com/LawnchairLauncher/lawnicons/pull/2071

**Comment by x9136** [comment]
@Hamster45105 Hey! Thanks. I'll send the checklist here tomorrow.

**Comment by x9136** [comment]
Hey! Thanks for the contribution. While there is no reviewer, you can do a self-review. This will help to fix the reasons why icons may not be suitable for Lawnicons. 

### Canvas and sizes [→](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#canvas--sizes)
1. Canvas: `192×192px`.
2. Non-square icons: the long side of an icon should be `160px`.
3. Square icons: `154×154px`.

### Color, stroke width and rounding [→](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#foundation)
1. Color: black `#000`.
2. No fill. Base stroke width: `12px`. `14px`, `10px`, `8px` — depending on the shape of the icons. `6px` — for fine details.
3. Rounded ends and joins. 90° corners are rounded by `6-32px`.

### Naming [→](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#naming)
1. Names should match the official ones and contain no additional text.
2. If the original name is not in English, then add a localized or transliterated one to it using `~~`.
Example: `フールー ~~ Hulu`.
3. The names of the drawables should repeat the names of the apps if nothing prevents it.

### Quality [→](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#details)
1. Icons should be easily recognizable.
2. No blackness. Reduce the stroke width or simplify the icons so that there are no noticeable black spots.
3. Avoid close distances between strokes. The icons on the phone screen will be smaller, so the small distances between the strokes will stick together.
5. Avoid drastic changes in stroke widths. When the strokes next to each other differ in width by 4px or more, the icon will look sloppy.

**Comment by Hamster45105** [comment]
Thanks, I've added the proper checklist in now.

**Comment by x9136** [comment]
Reopened because it doesn't work. #2098
