### ISSUE TITLE
Icon Request: Tachiyomi, Quicknovel, Material Files, Twitch Mod, Shosetsu

### ISSUE THREAD

**Issue by Chamousselama** [LawnchairLauncher/lawnicons#208]
It would be appreciated if these apps were added

TachiyomiJ2K (eu.kanade.tachiyomi.j2k)
Quicknovel (com.lagradost.quicknovel)
Material Files (me.zhanghai.android.files)
Twitch Mod (tv.twitchmod.android.app)
Shosetsu (com.github.doomsdayrs.apps.shosetsu.debug)

Both twitch mod and material files could their existing counterparts like twitchmod  --->  twitch
Material files ---> google files

**Comment by sdl820** [comment]
Icon request! 

I'd appreciate it if there was a Pandora music icon  :)

**Comment by koukichi7010** [comment]
This has been a request for 175....idk if it will be added though 😩
