### ISSUE TITLE
Buttons In App Don't Work

### ISSUE THREAD

**Issue by Hamster45105** [LawnchairLauncher/lawnicons#2086]
### About this discussion

There are a few buttons in the Lawnicons app that don't seem to work:

1. "View on GitHub" button on icon preview dialog
2. "GitHub" button on about page

Obviously, this should be fixed to make them functional.

**Comment by x9136** [comment]
Maybe you have a version before 2.9.0?

**Comment by Hamster45105** [comment]
> this error is not present in the latest release version and the latest dev version.

I'm on the latest debug version:

![Lawnicons.png](https://github.com/LawnchairLauncher/lawnicons/assets/133548095/e57aadd5-5a32-4ebb-a701-dea94c896581)

Tapping on the buttons just does nothing.

**Comment by x9136** [comment]
> Tapping on the buttons just does nothing.

The issue does not apply to all devices, or is related to something else.

https://github.com/LawnchairLauncher/lawnicons/assets/60105060/75add377-d179-4af9-906e-d0c92c31037c
MIUI 12.5.2 A11.

**Comment by Hamster45105** [comment]
> The issue does not apply to all devices

For reference I am using One UI 6.0.

It would be good if someone else could reproduce this issue.

**Comment by service-paradis** [comment]
Same here. Those buttons does not work in the latest app version on Pixel 7 Pro (Android 14).

**Comment by x9136** [comment]
Everything works as it should on Samsung with A14. At the moment, it is unclear what the bug is related to, so how to fix it is also unclear.

**Comment by Hamster45105** [comment]
Appears to be fixed in the latest debug version. @service-paradis can you confirm this?
