### ISSUE TITLE
Huawei phone app not themed

### ISSUE THREAD

**Issue by Yurieaijoker** [LawnchairLauncher/lawnicons#213]
Huawei phone app is linked to the dialer icon but its still not themed. 
![Screenshot_20211222_162710_app lawnchair](https://user-images.githubusercontent.com/93813352/147060741-fa0951bd-5af1-40b7-8058-b13e553de622.jpg)

**Comment by im-coder-lg** [comment]
How did you enable Lawnicons on Lawnchair 12? Can you tell me?

**Comment by Yurieaijoker** [comment]
![Uploading Screenshot_20220125_112407_app.lawnchair.jpg…]()
Enable themed icon toggle

**Comment by im-coder-lg** [comment]
I did that but it still doesn't work. I want it to apply globally on Lawnchair.

**Comment by Yurieaijoker** [comment]
What version of lc are you using?

**Comment by Yurieaijoker** [comment]
Use alpha 4

**Comment by im-coder-lg** [comment]
That's what I use.

**Comment by Yurieaijoker** [comment]
Send screen shot

**Comment by Yurieaijoker** [comment]
Are all of the icons not themed?

**Comment by im-coder-lg** [comment]
Nope, only the homescreen is.

**Comment by Yurieaijoker** [comment]
Well the lawincons is called themed icons cause it is onpy applied in the home screen

**Comment by SuperDragonXD** [comment]
If the package name is `com.huawei.camera`, it has been added in the latest release. Update Lawnicons & Lawnchair to see the icon themed.
