### ISSUE TITLE
Transparent themed icon "black" on Home screen 

### ISSUE THREAD

**Issue by Zero00000000000000000000** [LawnchairLauncher/lawnicons#2168]
### About this discussion

Light mode the transparent icon on home screen are black they are jst mess with wallpaper...and there is no option to change color on transparent themed icons
![Uploading Screenshot_20240618-211402_Lawnchair.png…]()
![Uploading Screenshot_20240618-211402_Lawnchair.png…]()

**Comment by x9136** [comment]
Hey! You didn't wait for the screenshots to be uploaded, so there aren't any. In any case, if you are using Lawnchair, it is better to look for this issue there.

https://github.com/LawnchairLauncher/lawnchair/issues
