### ISSUE TITLE
[Icon Update] ProtonVPN

### ISSUE THREAD

**Issue by abhishek-junghare** [LawnchairLauncher/lawnicons#2243]
### Icons

The icon for ProtonVPN is there, but is not getting applied. Following are package details -

**Mapped components (from Lawnicons):**
ch.protonvpn.android/
com.protonvpn.android.ui.onboarding.SplashActivity

**Package names (from Package Name Viewer):**
ch.protonvpn.android
ch.protonvpn.android.RoutingActivity

**Comment by x9136** [comment]
#2220
If that's what you're talking about, then please close the issue yourself.

**Comment by abhishek-junghare** [comment]
Yes
