### ISSUE TITLE
Scrollbar Broken

### ISSUE THREAD

**Issue by Hamster45105** [LawnchairLauncher/lawnicons#2256]
### About this discussion

The scrollbar in the app is not functioning as it should. The letter is not updating and is just staying as **#**. In addition it goes off the bottom of the page underneath the toolbar.

https://github.com/user-attachments/assets/56de99b2-2808-4c92-a695-5987e815506c

**Comment by SuperDragonXD** [comment]
The scrollbar label is intentionally non-functional for this release, as fixing it requires additional changes (and Lawnicons is overdue by 1 month in terms of the release schedule).

I plan on fixing this as well soon.

**Comment by SuperDragonXD** [comment]
Re-opening this issue with label, until we release Lawnicons 2.12.0.
