### ISSUE TITLE
DataBackup

### ISSUE THREAD

**Issue by elisenlebkuch** [LawnchairLauncher/lawnicons#2257]
### Icons

old logo: 
![Screenshot_2024-08-13-00-34-49-95_29c0a1e3aaa5223e1ffcd3f9ab52a346](https://github.com/user-attachments/assets/b43b41e0-ccf0-40cb-a293-d3c10dd3f93e)

that's how it currently looks in lawnicons: 
![Screenshot_2024-08-13-00-38-49-14_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/c6b7296d-24fc-450d-86d4-29dc669fc5c0)

new logo: 
![icon](https://github.com/user-attachments/assets/5ef2d06d-3cd5-44c1-b2aa-c00b1b218bc3)

**Comment by x9136** [comment]
It looks like this icon was made by AI.

I suggest this option. What do you say?
![Screenshot 2024-08-14 at 17 12 18](https://github.com/user-attachments/assets/d93356bb-db0f-4560-9681-2fddd7cbb0fa)

**Comment by elisenlebkuch** [comment]
Yes I think it looks good.
