### ISSUE TITLE
Update Spotify icon to match current icon

### ISSUE THREAD

**Issue by SomeoneElse00** [LawnchairLauncher/lawnicons#2265]
### Icons

Spotify, [spotify.svg](https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs/spotify.svg) --> Spotify, [current icon listed in google play](https://play-lh.googleusercontent.com/7ynvVIRdhJNAngCg_GI7i8TtH8BqkJYmffeUHsG-mJOdzt1XLvGmbsKuc5Q1SInBjDKN=w240-h480)

### Additional information

Thoughts on adding the circle around the lines in the logo? It feels like a part of the logo is missing. The current icon also feels off-center (yes, I know the lines are off-center in the normal logo), but adding the circle would visually correct that.

**Comment by x9136** [comment]
> Thoughts on adding the circle around the lines in the logo?

The uniqueness will decrease because there are hundreds of circle icons.

> The current icon also feels off-center

This can be improved.
