### ISSUE TITLE
プロセカ can use the same icon with HATSUNE MIKU: COLORFUL STAGE!

### ISSUE THREAD

**Issue by Akowu229** [LawnchairLauncher/lawnicons#2281]
### About this discussion

These both are the same game, just different server. So I figured that they can probably just share the hatsune-miku-colorful-stage icon.

プロセカ com.sega.pjsekai/com.google.firebase.MessagingUnityPlayerActivity

HATSUNE MIKU: COLORFUL STAGE!
com.sega.ColorfulStage.en/com.google.firebase.MessagingUnityPlayerActivity

**Comment by x9136** [comment]
You can also do it yourself.
https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#adding-an-icon-to-lawnicons
