### ISSUE TITLE
Issue: icon size is broken

### ISSUE THREAD

**Issue by incycledream** [LawnchairLauncher/lawnicons#230]
Camera Go (com.google.android.apps.cameralite) and DriveDroid (com.softwarebakery.drivedroid) icons size is broken
![IMG_20220104_015449_558](https://user-images.githubusercontent.com/81514356/147992695-80611b3b-4610-47f2-b954-a4879140205d.jpg)

but when I try to drag icon size changes to normal

https://user-images.githubusercontent.com/81514356/147992726-1390c358-8d42-4808-80a4-9e9759464cbd.mp4

Device: Redmi Note 9S (curtana)
Android version: 11
Lawnchair version: 12.0 (619)
Lawnicons version: 107

**Comment by oli0371** [comment]
Just apply an icon pack with adaptive icons this will fix the issue

**Comment by Chefski** [comment]
Any update on the issue? Do you still experience this?

**Comment by obvionaoe** [comment]
Any updates on why this is happening?

**Comment by Chefski** [comment]
I tried to find any issues relating to this on the Lawnchair repo but couldn't find anything.

**Comment by x9136** [comment]
I suggest installing [Lawnchair 14 Beta 2](https://lawnchair.app/downloads/), the latest version of Lawnicons, and let us know if the problem still occurs.
