### ISSUE TITLE
Pixeldroid doesn't display existing icon

### ISSUE THREAD

**Issue by chrostino** [LawnchairLauncher/lawnicons#2308]
### About this discussion

org.pixeldroid.app already has a Lawnicons icon and used to work fine. Nothing has changed, neither the icon design nor the package name, but now it its lawnicons icon doesn't display anymore, as if it doesn't have one

**Comment by x9136** [comment]
Then the app activity could change.

**Current activities in Lawnicons**
```
org.pixeldroid.app/org.pixeldroid.app.main.MainActivity
org.pixeldroid.app/org.pixeldroid.app.MainActivity
```

**Comment by chrostino** [comment]
where do I check and how do I report the new one

**Comment by x9136** [comment]
I see. This activity was added a couple of weeks ago. You can wait for Lawnicons v2.12 or [download the development build](https://github.com/LawnchairLauncher/lawnicons?tab=readme-ov-file#download).

**Comment by x9136** [comment]
[Lawnicons 2.12](https://github.com/LawnchairLauncher/lawnicons/releases/tag/v2.12.0)

**Comment by chrostino** [comment]
just updated to 2.12 (from izzyondroid f-droid repo), the issue persists
