### ISSUE TITLE
New app Icon in latest version on Droidify

### ISSUE THREAD

**Issue by CurseUser123** [LawnchairLauncher/lawnicons#2363]
### Icons

Drawable: easter_eggs

Mapped components: 
Easter Eggs:
com.dede.android_eggs/com.dede.android_eggs.main.EasterEggsActivity
com.dede.android_eggs/com.dede.android_eggs.views.main.EasterEggsActivity

![Screenshot_2024-09-19-18-24-45-06_bf5286d428c97f865e4b51a5afbaefcd](https://github.com/user-attachments/assets/3d34697a-4394-4e61-b2e8-43569074916b)

**Comment by x9136** [comment]
#2344
