### ISSUE TITLE
OLX Rebranding 

### ISSUE THREAD

**Issue by Chromeyyy** [LawnchairLauncher/lawnicons#2367]
### Icons

OLX has been rebranded to dubizzle.
OLX, [olx.svg](svgs/olx.svg) ==> Dubizzle, [dubizzle logo](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEqVnitDV9pjuFD1AlUHS7KcJEQOO9rxwpdE5PxbADagdpODtK4nrqpQ&s=10)

**Comment by x9136** [comment]
I believe this only applies to:
```
<item component="ComponentInfo{com.olxmena.horizontal/com.empg.olxeg.MainActivity}" drawable="olx" name="OLX" />
```
