### ISSUE TITLE
My Tele2 is rebranding to My t2 with new logo

### ISSUE THREAD

**Issue by rmAlt1** [LawnchairLauncher/lawnicons#2416]
### Icons

![Screenshot_2024-10-19-16-55-20-93_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/8ac633d0-76fe-4ef1-afca-e97e4b349afa)
![Screenshot_2024-10-19-16-40-01-05_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/user-attachments/assets/33558e5d-f3c5-4eeb-8065-49c4a2862d82)

![155e0476-c5cf-439d-abba-ae3714c75347](https://github.com/user-attachments/assets/632cec90-71b5-49f2-9351-a5b4284f3206)

ru.tele2.mytele2

**Comment by x9136** [comment]
#2342
