### ISSUE TITLE
Individual Icon Customization

### ISSUE THREAD

**Issue by Kaisar870** [LawnchairLauncher/lawnicons#2427]
### About this discussion

I've noticed, I can't customize the icon individually, which is available on previous version. For example, hold any icon and customize I can pick any icon for Icon gallery which is remove recent version. Any workaround?

**Comment by x9136** [comment]
Do you use Lawnchair?
https://github.com/LawnchairLauncher/lawnchair/issues/4875

> Any workaround?

You may have updated Lawnchair in the last month, then installing an older version of Lawnchair should help.

Regarding other launchers, you need to check on which version of Lawnicons everything is broken.
