### ISSUE TITLE
realme launcher possibility to change icon shape?

### ISSUE THREAD

**Issue by SteQuOFFICIAL** [LawnchairLauncher/lawnicons#2451]
### About this discussion

Is it possible to somehow change the icon shape in realme launcher? Or maybe there is a chance that it will appear in a future update?

**Comment by SuperDragonXD** [comment]
Icon pack icon shapes are handled by the current launcher and not the icon pack itself. As such, it depends on whether Realme Launcher supports changing the icon shape or not.
