### ISSUE TITLE
com.smart.consumer.app update...

### ISSUE THREAD

**Issue by freakingdan** [LawnchairLauncher/lawnicons#2457]
### Icons

its package class got changed into this...

![Screenshot_20241121-152750](https://github.com/user-attachments/assets/acc158ec-21ba-404f-a47e-736f2ff81e04)

i dont know if you would update it or not?

**Comment by x9136** [comment]
Please add new links through new PRs, not through issues.
![Screenshot 2024-11-21 at 14 00 11](https://github.com/user-attachments/assets/976547cb-9086-4d43-a4dd-15ec526d78f4)
https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#adding-an-icon-to-lawnicons
