### ISSUE TITLE
Auto adaptive icons broken

### ISSUE THREAD

**Issue by XcutionerX** [LawnchairLauncher/lawnicons#252]
Turning on auto adaptive icons in Lawnchair settings > General breaks theming for icons without adaptive icons. For example, Play games and Google assistant.

**Comment by oli0371** [comment]
I got this issue too.. try using latest devs build of lawnchair this will fix the issue

**Comment by SuperDragonXD** [comment]
I can't tell whether this issue is fixed or not, but it's likely fixed (as said by above) on the later releases. Closing this issue.
