### ISSUE TITLE
Icon Request: Samsung Game Launcher, Zarchiver, IstanbulKart, Papara

### ISSUE THREAD

**Issue by CanKolay3499** [LawnchairLauncher/lawnicons#254]

**Comment by CanKolay3499** [comment]
![Screenshot_20220120-162832_Lawnchair](https://user-images.githubusercontent.com/80613396/150347909-b6aa289d-8a94-4464-9722-45f1b9cdb867.jpg)
![Screenshot_20220120-162820_Lawnchair](https://user-images.githubusercontent.com/80613396/150347916-8682ae87-a9d5-4819-b43d-295856ed9907.jpg)
![Screenshot_20220120-162807_Lawnchair](https://user-images.githubusercontent.com/80613396/150347919-24013a83-af7d-4240-b117-70bce3b54ef3.jpg)
![Screenshot_20220120-162754_Lawnchair](https://user-images.githubusercontent.com/80613396/150347922-e47ec081-f648-452e-8d74-a69e92572d5b.jpg)

**Comment by CanKolay3499** [comment]
Package names:
- Zarchiver: ru.devs.zarchiver
- Papara: com.mobilium.papara
- IstanbulKart: com.belbim.istanbulkart
- Game Launcher: com.samsung.android.game.gamehome

**Comment by oli0371** [comment]
In my folk i already add icons for zarchiver and zarchiver pro now need to wait devs for checking my pr

**Comment by lawnchairci** [comment]
Hello! It would appear that this icon request doesnʼt include the package names of some or all of the apps for which icons have been requested. In addition, we are switching to a new system for icon requests. The apps for which package names have been provided (if such apps exist in this icon request) have been added to the new icon request database, meaning no action is required. For the apps for which package names havenʼt been provided, please submit an icon request via the new icon request form: https://forms.gle/Fx8vZAiWdW1Tyjo57.
