### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by brxken128** [LawnchairLauncher/lawnicons#255]
I can't find any documentation or a single issue that mentions how to use this icon set, it's all just icon requests for obscure apps that nobody has ever heard of.

Any guidance to using these icons with Lawnchair Launcher would be greatly appreciated, thank you so much.

**Comment by oli0371** [comment]
You just have to install lawnicons the turn on themed icons.. this is not an icon pack but an add-on to apply google monet on 3rd party apps.

**Comment by brxken128** [comment]
> You just have to install lawnicons the turn on themed icons.. this is not an icon pack but an add-on to apply google monet on 3rd party apps.

Except there's no release APKs, it's not on the play store and the only APKs I can find are from GitHub's debug CI/CD, and installing that shows the icons but doesn't make them available for selection in Lawnchair.

**Comment by brxken128** [comment]
After realising we're supposed to install the CI/CD debug APK, I did just that and no icons are showing in Lawnchair settings. I've tried rebooting, clearing cache, reinstalling, the while nine yards
