### ISSUE TITLE
Feature Request: Making LawnIcons like an icon pack

### ISSUE THREAD

**Issue by daBroma** [LawnchairLauncher/lawnicons#289]
I would like to have the Lawnicons.apk act as an icon pack. So I could apply it in other launchers and use Shortcut maker to compensate for the missing icon in LawnIcons.

**Comment by julianfairfax** [comment]
I would like so I can have my Lawnicons everywhere in Lawnchair, and so I can use per-icon customisation to set them for apps that aren't yet supported

**Comment by SuperDragonXD** [comment]
I'd recommend changing the title to something similar to "Per App Icon customization of Lawnicons" or similar, to clarify the title. There are many duplicate issues about this, so renaming it would be great.

**Comment by KevoM** [comment]
This feature could also benefit for users of Lawnchair 2...

**Comment by sethgillett** [comment]
Any updates / progress on this?
