### ISSUE TITLE
develop vs main-wip branch

### ISSUE THREAD

**Issue by JordyEGNL** [LawnchairLauncher/lawnicons#290]
I recently noticed that the icons in the `main-wip` branch have a completely different design than those in the `develop` branch. Any information on that? Will there be 2 icon-packs? Can people choose between them?

**Comment by halacoglu** [comment]
It looks like `main-wip` includes mainly line icons. Current `developer` branch includes both line and filled icons, thus creating inconsistency. Would be so cool to choose from line and filled icon packs.

**Comment by JordyEGNL** [comment]
> It looks like `main-wip` includes mainly line icons. Current `developer` branch includes both line and filled icons, thus creating inconsistency. Would be so cool to choose from line and filled icon packs.

Hopefully people can choose between the design :)

**Comment by Yurieaijoker** [comment]
Totally agree 👍 it would be great to have an option tp choose between outline and filled icons.

**Comment by halacoglu** [comment]
Looks like we have a new style alongside with lines and filled: `gradient` I saw it here #301 and applied on my `Flamingo` icon here #275 and it worked. The only downside is gradient is inverted when dark mode is enabled but still, it looks cool!

![Screenshot_1643468656](https://user-images.githubusercontent.com/30694379/151666907-9adfb3bf-29de-443c-a5db-cfeee08461c2.png)

**Comment by JordyEGNL** [comment]
> Looks like we have a new style alongside with lines and filled: `gradient` I saw it here #301 and applied on my `Flamingo` icon here #275 and it worked. The only downside is gradient is inverted when dark mode is enabled but still, it looks cool!
> 
> ![Screenshot_1643468656](https://user-images.githubusercontent.com/30694379/151666907-9adfb3bf-29de-443c-a5db-cfeee08461c2.png)

I'm not sure if thats allowed, but we'll see 😄

**Comment by JordyEGNL** [comment]
@patrykmichalik is it true that the develop branch will no longer be updated and released on the play store? Only support for main-wip?

**Comment by RikKoedoot** [comment]
Yes that's true, we've told you before.

**Comment by patrykmichalik** [comment]
`main-wip` contains a redesign of Lawnicons and will soon be merged into `develop`. The new icon style will be used for the public release of Lawnicons. The reason for the redesign is that the icon set present on the `develop` branch is relatively inconsistent (see image). Unfortunately, we don’t currently have the capacity to provide two styles to choose from.

![2022-02-02-180326_528x263_scrot](https://user-images.githubusercontent.com/56888459/152201685-3340f425-1cf9-4ecb-aff3-7529600799e1.png)

**Comment by prayag17** [comment]
I think the icons should have been just the stock app icons weather they are thin or filled, they shouldn't be styled based on another design language
