### ISSUE TITLE
My pull-request #279 added duplicates

### ISSUE THREAD

**Issue by JordyEGNL** [LawnchairLauncher/lawnicons#302]
HI, I just noticed that my pr #279 did add duplicates. 
This is the sorted list, maybe an editor can change it directly.
[grayscale_icon_map.xml.md](https://github.com/LawnchairLauncher/lawnicons/files/7964029/grayscale_icon_map.xml.md)

@patrykmichalik I think you can edit this directly? Thanks

**Comment by patrykmichalik** [comment]
Thanks for reporting the error, @JordyEGNL! I’ve resolved this with commit 25479e2e8e8cfc86c007164c257d904fe159b83a.
