### ISSUE TITLE
Icon request: Paytm & Money Lover

### ISSUE THREAD

**Issue by ImSShivs** [LawnchairLauncher/lawnicons#325]
Hello,
Please add below apps in Lawnicons as well.

These apps are my daily driver but as they are not supported dynamic theming. They
kinda bumming my homescreen aesthetic.

1- Paytm
https://play.google.com/store/apps/details?id=net.one97.paytm

2- Money Lover
https://play.google.com/store/apps/details?id=com.bookmark.money

Both these apps are widely used with millions of installations.

Thanks

![Screenshot_2022-02-03-09-52-17-92_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/24227393/152358479-f7fd08f7-03f6-4f55-91ba-4f822202cae1.jpg)
![Screenshot_2022-02-03-09-48-36-97_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/24227393/152358496-c554c17b-7d11-40a0-9396-6f836a067c39.jpg)
![Screenshot_2022-02-03-09-48-17-19_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/24227393/152358510-7fc396d4-f28f-4cc0-a52e-f2375d93b09f.jpg)

**Comment by lawnchairci** [comment]
Hello! It would appear that this icon request doesnʼt include the package names of some or all of the apps for which icons have been requested. In addition, we are switching to a new system for icon requests. The apps for which package names have been provided (if such apps exist in this icon request) have been added to the new icon request database, meaning no action is required. For the apps for which package names havenʼt been provided, please submit an icon request via the new icon request form: https://forms.gle/Fx8vZAiWdW1Tyjo57.
