### ISSUE TITLE
Google Meet app not themed

### ISSUE THREAD

**Issue by TeaspoonOnTheTable** [LawnchairLauncher/lawnicons#335]
![ThisIsAnImage](https://user-images.githubusercontent.com/97811600/152615962-aa6433bf-25d2-4de4-b840-eb5942764520.jpg)

After updating to Lawnchair 12 Alpha 5, the Google Meet `(com.google.android.apps.meetings)` app icon not themed.

**Comment by IAmRuMaks** [comment]
[Update to Lawnicons 1.0.0](https://github.com/LawnchairLauncher/lawnicons/releases/tag/v1.0.0)

**Comment by TeaspoonOnTheTable** [comment]
I've updated to Lawnicons 1.0.0 version. But a lot of icons of my apps are unthemed and I'm not a fan of outlined icons (Main-Wip?) tho. Is there an option to switch from outlined icons to filled icons?

**Comment by IAmRuMaks** [comment]
I opened a pull request that fixes this issue: #353
Until it gets merged you can use [this](https://mega.nz/file/4JwQnDiI#eOaTK5QesA89Ogz0bL9-nkMqX6WFOFpAkFt3pq2lNRY) build
