### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Matei399YT** [LawnchairLauncher/lawnicons#370]
Icon for Motorola Apps:
-Moto
-Interactive Wallpaper
-Audio Effects
-Device Help(Moto Help)
-Moto Camera 2
-Moto Camera 3
Icon for Pulse Music
Icon for ESET Security

**Comment by lawnchairci** [comment]
Hello! It would appear that this icon request doesnʼt include the package names of some or all of the apps for which icons have been requested. In addition, we are switching to a new system for icon requests. The apps for which package names have been provided (if such apps exist in this icon request) have been added to the new icon request database, meaning no action is required. For the apps for which package names havenʼt been provided, please submit an icon request via the new icon request form: https://forms.gle/Fx8vZAiWdW1Tyjo57.
