### ISSUE TITLE
Lawnicons Not Working

### ISSUE THREAD

**Issue by sunaxl13** [LawnchairLauncher/lawnicons#374]
Hellow I Need Help Lawnchair cannot detect the lawnicons app I tried to reboot, uninstall and install but it still doesn't work please help me
![Screenshot_20220210-112648](https://user-images.githubusercontent.com/97773166/153331501-c8863a37-5c3d-4801-a252-ab82f8721f51.png)

**Comment by kazooduck** [comment]
you need an Icon pack under it to work

**Comment by sunaxl13** [comment]
Thank You! @kazooduck 
![Screenshot_20220210-120448](https://user-images.githubusercontent.com/97773166/153335082-2b0c9afc-7917-4025-a6d4-1a73787b8289.png)
 My Problem Is Fixed

**Comment by FPMilan** [comment]
How did you fix it?

**Comment by sunaxl13** [comment]
> How did you fix it?

I Installed an
![Screenshot_20220304-133848](https://user-images.githubusercontent.com/97773166/156706177-bcb6d587-8bc1-4e43-8172-3ad8ebfd2ce8.png)
 icon pack

**Comment by FPMilan** [comment]
Did the same, but now the icon pack is active but not the lawnicons 🤔
![Uploading Screenshot_20220304-074038.png…]()

**Comment by Yurieaijoker** [comment]
Lawnicons is not an icon pack its just a themed icons that can be applied on the homescreen by enabling the themed icons toggle on general setting of lawnchair

**Comment by FPMilan** [comment]
I am afraid that I don't have this setting. Can you share a screenshot please? My install is in German and I can't tell which setting translates to "Themes Icons". Thank you!

**Comment by Yurieaijoker** [comment]
![Screenshot_20220304_164040_app lawnchair](https://user-images.githubusercontent.com/93813352/156729263-a9855ef4-400d-41dd-8ae4-19329eb21aa5.jpg)

**Comment by FPMilan** [comment]
thank you @Yurieaijoker, turns out I had the wrong version installed (Play Store) reinstalled the version from telegram and it works just as expected :)
