### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by leifniem** [LawnchairLauncher/lawnicons#39]
Hey pals,

could you add a CONTRIBUTING.md file to the repo? We've got all the Delta Icons as SVGs, so could probably help you out with some stuff :)

Cheers!

**Comment by ankitvrsharma** [comment]
Just put your (svg+xml) in svgs folder add xml in drawables and connect your drawables to package name in grayscale icon xml

**Comment by patrykmichalik** [comment]
Thanks for your interest in contributing, @leifniem! I’ll add a `CONTRIBUTING.md` file shortly.

**Comment by patrykmichalik** [comment]
Done! If anything is unclear, feel free to let me know. I’ll be happy to help.

**Comment by leifniem** [comment]
Nope, perfectly clear, thank you @patrykmichalik i hope i'll find time this year to add some icons, have to finish my thesis first sadly

**Comment by patrykmichalik** [comment]
Thanks, @leifniem! Best of luck with your thesis.
