### ISSUE TITLE
Huawei/Honor camera icon 

### ISSUE THREAD

**Issue by Abs-30** [LawnchairLauncher/lawnicons#41]
The lawnicons aren't themeing the huawei/honor camera icons
Package names
com.huawei.camera
com.honor.camera

**Comment by patrykmichalik** [comment]
Hello! Iʼve just linked the camera icon to the “com.huawei.camera” and “com.honor.camera” packages.

**Comment by Abs-30** [comment]
Awesome. Thanks👌

> Hello! Iʼve just linked the camera icon to the “com.huawei.camera” and “com.honor.camera” packages.
