### ISSUE TITLE
Add tutorial how to create icons and contribute

### ISSUE THREAD

**Issue by FPMilan** [LawnchairLauncher/lawnicons#417]
Would like to create icons myself, just don't know how to get started

**Comment by FPMilan** [comment]
In the meantime, I managed to create clean .svg icon files and to fork the main repo into Android Studio. 
How can I now create the .xml file with the <vector> property? Is this a manual process or can I generate it automatically somehow?
Any hint is appreciated :)

(Is my assumption correct that it suffice to submit the three changes:
1. app\src\main\res\<icon>.xml
2. svgs\<icon>.svg
3. add a line in app\src\main\res\xml\grayscale_icon_map.xml ?)

**Comment by xV8IHmeZIAStqNFV8iKGyyertVIet15TS6gWrIV** [comment]
Look at the CONTRIBUTING.md file
