### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by SuperDragonXD** [LawnchairLauncher/lawnicons#418]
Looks like this repo does not have a `README.md` file or similar. Maybe it could be added for additional information about this, and links to several stuff?

**Comment by FPMilan** [comment]
my suggestion is to change the contibuting.md to be the readme.md, as it is easy to overlook + anyone visiting the github repo will anyways be here to help (imho)

**Comment by SuperDragonXD** [comment]
Maybe a link to [CONTRIBUTING.md](CONTRIBUTING.md) could be better.

Also, made a PR for this (#421

**Comment by SuperDragonXD** [comment]
Also, should I add a link to [LICENSE](https://github.com/LawnchairLauncher/lawnicons/blob/develop/LICENSE) in the README file?

**Comment by SuperDragonXD** [comment]
Any update on this?
