### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by mintyleaf** [LawnchairLauncher/lawnicons#447]
Owlgram has experimental monet style icon, but it smaller than others, and not in that new "thin linish" style 

https://iconpusher.com/device/c70cab805f78506a/it.owlgram.android

![Screenshot_20220425-170945~2.png](https://user-images.githubusercontent.com/17470408/165095718-4d27c64e-72d4-40dc-9cca-a21f2c03c389.png)

**Comment by SuperDragonXD** [comment]
Late, but not sure if "Icon request" is the best title for this. Maybe change it to something more specific?

**Comment by REM-Codes** [comment]
> Late, but not sure if "Icon request" is the best title for this. Maybe change it to something more specific?

Possibly "icon update request"?

**Comment by SuperDragonXD** [comment]
Sure I guess?

**Comment by Chefski** [comment]
Issue is solved in #655
