### ISSUE TITLE
Lawnicons please

### ISSUE THREAD

**Issue by reechings** [LawnchairLauncher/lawnicons#45]
Gallery Go, Facebook Lite, XDA developers and Tapatalk Pro icons please.

**Comment by reechings** [comment]
Thank you for Gallery Go, do I need to make new request for Facebook Lite, Tapatalk Pro and XDA app?

**Comment by patrykmichalik** [comment]
PR #58 also introduced icons for Tapatalk Pro and XDA. As for Facebook Lite, I must have not noticed that it was listed in this issue, causing me to close it prematurely. Sorry about it! I’ve just linked our existing Facebook icon to Facebook Lite.
