### ISSUE TITLE
Lite apps

### ISSUE THREAD

**Issue by 54m33r4** [LawnchairLauncher/lawnicons#46]
Map lite apps to their base apps😇

Facebook lite
Instagram lite
Twitter lite
Spotify lite

**Comment by Rixon46** [comment]
Share the package name for these apps

**Comment by 54m33r4** [comment]
@Rixon46 
Facebook lite - com.facebook.lite
Instagram lite - com.instagram.lite
Twitter lite - com.twitter.android.lite
Spotify lite - com.spotify.lite
Messenger lite - com.facebook.mlite
Google Go (google lite) - com.google.android.apps.searchlite
Maps Go (Google Maps lite) - com.google.android.apps.mapslite

those are all the lite/go apps I know and I wish it would be great if the main icons are linked.
Thanks <3

also for samsung clock (if possible) - com.sec.android.app.clockpackage
