### ISSUE TITLE
It's not showing phone app icon instead of that it's showing contact app icon

### ISSUE THREAD

**Issue by Rixon46** [LawnchairLauncher/lawnicons#462]
it's not showing phone app icon instead of that it's showing contact app icon 
It's miui dialer app

rom: miui 12 based on android 9

**Comment by Chefski** [comment]
Whats the package name for the dialer app?

**Comment by Chefski** [comment]
@Rixon46 do you still experience this issue?

**Comment by KTibow** [comment]
I'm experiencing this issue on a OnePlus 7 Pro, even though according to the Icons Request app they should be differentiated.

**Comment by x9136** [comment]
#1728 — the main topic for the issue with the dialer icon.

If the activity is mapped correctly, then there is a possible workaround:

1. Install Lawnchair 14.
2. Home Settings → General → Icon Style → Lawnicons + set Themed Icons to "Home Screen & App Drawer".
