### ISSUE TITLE
Icons have incorrect, different sizes.

### ISSUE THREAD

**Issue by DavidRLTG** [LawnchairLauncher/lawnicons#471]
![Screenshot_20220520-094005_Lawnchair](https://user-images.githubusercontent.com/87834635/169468415-0f207714-9207-4946-9d71-9ba3e9f1084f.png)
I am terrified

**Comment by DavidRLTG** [comment]
(The chrome icon is VERY SLIGHTLY bigger )

**Comment by Chefski** [comment]
Not sure if the icon was previously bigger but its now 160x160 as icons should be

**Comment by mluizvitor** [comment]
I'm designing new icons and I can confirm.

![image](https://user-images.githubusercontent.com/57257682/192029712-2ee0b396-6e0f-44da-9802-e18054d397e7.png)

**Comment by Chefski** [comment]
This is due to scaling done by the launcher, not the icons the themselves.

I'll be marking this issue as a duplicate as it's already been pointed out in #230
