### ISSUE TITLE
Showing contact app icon instead of dialer app icon

### ISSUE THREAD

**Issue by Rixon46** [LawnchairLauncher/lawnicons#489]
link the miui dialer app icon with dialer icon currently its showing contact app icon instead of dialer app icon

**Comment by N0-0NE-Dev** [comment]
can you tell me the package name please

**Comment by SuperDragonXD** [comment]
(since above didn't work) Duplicate of #462

**Comment by SuperDragonXD** [comment]
Duplicate of #462
