### ISSUE TITLE
Specify Icon for App

### ISSUE THREAD

**Issue by REM-Codes** [LawnchairLauncher/lawnicons#559]
Please add a feature that lets you choose a lawnicon for an app that doesn't have one. Moto Camera doesn't have an icon, but there is a camera icon in lawnicons. I'd like to be able to set the camera app's icon to the lawnicon's camera icon.

**Comment by aalaap** [comment]
I came here to post this exact request. +1

**Comment by Seercat3160** [comment]
This would also be very useful for apps with inconsistent package names (for example when hiding the Magisk app). +1
