### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by flame-0** [LawnchairLauncher/lawnicons#567]
Hello, Maintainer(s)!

Would you mind creating the attached icons below, please?

Thank you!

| Icon | Name | Package Name |
|-|-|-|
| <img src="https://raw.githubusercontent.com/AdAway/AdAway/master/app/src/main/res/mipmap-xxxhdpi/icon_round.png" width="32"/> | [AdAway](https://github.com/AdAway/AdAway) | org.adaway |
| <img src="https://raw.githubusercontent.com/markusfisch/BinaryEye/f4af35ad4689ee32f4dbd582b446843bf91c7fb1/svg/ic_launcher.svg" width="32"/>| [Binary Eye](https://github.com/markusfisch/BinaryEye) | de.markusfisch.android.binaryeye |
| <img src="https://user-images.githubusercontent.com/40175769/174436898-2677ad90-9df9-46b4-9e3f-96c45bd29bac.png" width="32"/> | [Calendar](https://github.com/LineageOS/android_packages_apps_Etar) | org.lineageos.etar |
| <img src="https://user-images.githubusercontent.com/40175769/174436967-4ce9fc9d-8b6e-4af0-8a46-e0ceb6098a48.png" width="32"/> | [Clock](https://github.com/LineageOS/android_packages_apps_DeskClock) | com.android.deskclock |
| <img src="https://user-images.githubusercontent.com/40175769/174436644-bd2e75ab-85d0-4d44-a327-bb75e27da6a9.png" width="32"/> | [Collabora Office](https://github.com/CollaboraOnline/online/tree/master/android) | com.collabora.libreoffice |
| <img src="https://raw.githubusercontent.com/SimpleMobileTools/Simple-Draw/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png" width="32"/> | [Draw](https://github.com/SimpleMobileTools/Simple-Draw) | com.simplemobiletools.draw.pro |
| <img src="https://raw.githubusercontent.com/LawnchairLauncher/lawnicons/develop/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png" width="32"/> | [Lawnicons](https://github.com/LawnchairLauncher/lawnicons) | app.lawnchair.lawnicons |
| <img src="https://raw.githubusercontent.com/lesspass/lesspass/main/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png" width="32"/> | [LessPass](https://github.com/lesspass/lesspass/tree/main/mobile) | com.lesspass.android |
| <img src="https://user-images.githubusercontent.com/40175769/174436695-f0622bf5-0422-4b58-847c-e0f8c6715302.png" width="32"/> | [LibreTorrent](https://github.com/proninyaroslav/libretorrent) | org.proninyaroslav.libretorrent |
| <img src="https://user-images.githubusercontent.com/40175769/174436957-bfb5181e-98e0-4dbd-bb02-2c20d4d2b961.png" width="32"/> | [Music](https://github.com/LineageOS/android_packages_apps_Eleven) | org.lineageos.eleven |
| <img src="https://raw.githubusercontent.com/NeoApplications/Neo-Store/master/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png" width="32"/> | [Neo Store](https://github.com/NeoApplications/Neo-Store) | com.looker.droidify |
| <img src="https://user-images.githubusercontent.com/40175769/174436707-c580e3a2-9085-43c2-bd8d-1f23df875bf3.png" width="32"/> | [QKSMS](https://github.com/moezbhatti/qksms) | com.moez.QKSMS |
| <img src="https://user-images.githubusercontent.com/40175769/174436718-9c3032ab-6150-415d-9258-c90b1cec89c3.png" width="32"/> | [SD Maid](https://play.google.com/store/apps/details?id=eu.thedarken.sdm) | eu.thedarken.sdm |
| <img src="https://user-images.githubusercontent.com/40175769/174436976-6e3eb640-fb11-4a93-88f0-92a0047b6644.png" width="32"/> | SIM Menu | com.android.stk |
| <img src="https://f-droid.org/repo/net.typeblog.shelter/en-US/icon_SadI7N5owTo-UKqex_wGEQdfXb3rvqoD4y_DXKRRRl8=.png" width="32"/> | [Shelter](https://github.com/PeterCxy/Shelter) | net.typeblog.shelter |
| <img src="https://user-images.githubusercontent.com/40175769/174479415-1bab2509-68b1-4851-b8f5-d97079118185.png" width="32"/> | [Steam](https://play.google.com/store/apps/details?id=com.valvesoftware.android.steam.community) | com.valvesoftware.android.steam.community |
| <img src="https://user-images.githubusercontent.com/40175769/174436733-1791c407-f484-4c8c-8ee3-75bd7caeff01.png" width="32"/> | [Twidere X](https://github.com/TwidereProject/TwidereX-Android) | com.twidere.twiderex |
| <img src="https://user-images.githubusercontent.com/40175769/174438010-f9ea6ae5-3189-41cc-92c8-58e3535aa80d.png" width="32"/> | [Wild Rift](https://play.google.com/store/apps/details?id=com.riotgames.league.wildrift) | com.riotgames.league.wildrift |

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
