### ISSUE TITLE
Is there a way to merge all the pull request on my end?

### ISSUE THREAD

**Issue by gun4qmm7h** [LawnchairLauncher/lawnicons#572]
I don't want to keep checking every week if this is updated and I really want to try out the apps icon in pull request. Is there a way that I van just merge the pull request on my end?

**Comment by lorrding** [comment]
Hi, what I've done is I simply created a local branch that I never push to my fork and use it to build my own APK. Don't know if it's okay though, but it's only for personal use 🤷‍♂️

**Comment by blogmangit** [comment]
> I don't want to keep checking every week if this is updated and I really want to try out the apps icon in pull request. Is there a way that I van just merge the pull request on my end?

yes just fork the current branch and merge the requests but don't push it to the main branch you forked from.

**Comment by patrykmichalik** [comment]
Hello! You can achieve this as follows:

1. Clone/fork this repository.
2. For each PR in this repository, add the corresponding remote to your clone/fork of this repository (use `git remote add`).
3. For each newly added remote, merge the appropriate branch into the `develop` branch of your clone/fork of this repository.
