### ISSUE TITLE
ASUS Rog5 Dialer and Camera not changing to lawnicons

### ISSUE THREAD

**Issue by maheshrk06** [LawnchairLauncher/lawnicons#577]
Hi Teams,

Thanks all Dev's for the hard work, i am having one issue with icons , only dialer and camera is not converting.
 
Any help ?

Thanks
![Screenshot_20220615-014137050](https://user-images.githubusercontent.com/61411961/174497286-9331eb03-535c-4a90-a8b6-4144c3ef3332.jpg)

**Comment by lorrding** [comment]
Do you have the package name of those apps?

**Comment by maheshrk06** [comment]
@lorrding sure here it is

com.asus.dialer
com.asus.camera

**Comment by maheshrk06** [comment]
![Screenshot_20220623-035455835](https://user-images.githubusercontent.com/61411961/175163657-d3744191-15d0-416a-98cc-65388b37d534.jpg)
 @lorrding  still remains the same, other icon packs are replacing not lawnicons.

**Comment by maheshrk06** [comment]
@lorrding no rush 🙂 i took Merge pull request #483 debug artifact, upon installing that camera icon issue solved, but phone remains same 😞

**Comment by lorrding** [comment]
Exactly 😅 I've only made a push request here so you can either:

- Wait for it to be merge (hopefully someday)
- Clone the repo, merge the PR on your end and build the app yourself

**Comment by maheshrk06** [comment]
Thanks for the heads-up @lorrding🤩 , i haven't setup Android studio and sdk but i will do that and will try to build an artifact 👍
