### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by jasons393** [LawnchairLauncher/lawnicons#580]
Add all the icons from https://simplemobiletools.com/
And also,
Droid-ify/Neo Store
Feeder
KDE Connect
KeePassDX
Gboard
K-9 Mail
Material Files
PDF Viewer Plus
RethinkDNS
Riseup VPN
Tusky
Geometric Weather
Syncthing
Binary Eye
Auxio
Orbot
Organic Maps

**Comment by Dialynx** [comment]
Also please add icons for:
Privat24
Monobank
Caves(Roguelike)

(Don't want to make a duplicated request)

**Comment by lawnchairci** [comment]
Hello! It would appear that this icon request doesnʼt include the package names of some or all of the apps for which icons have been requested. In addition, we are switching to a new system for icon requests. The apps for which package names have been provided (if such apps exist in this icon request) have been added to the new icon request database, meaning no action is required. For the apps for which package names havenʼt been provided, please submit an icon request via the new icon request form: https://forms.gle/Fx8vZAiWdW1Tyjo57.
