### ISSUE TITLE
Failed to build debug apk on fork

### ISSUE THREAD

**Issue by flug8** [LawnchairLauncher/lawnicons#592]
Building an apk on my own fork isnt working fork: [flug8/lawnicons ](https://github.com/flug8/lawnicons/) 

![Screenshot_20220627-150138_Chrome](https://user-images.githubusercontent.com/80972789/175948734-7dce49ea-d55c-4733-a1cf-c4224aac33cf.jpg)

> /usr/bin/cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-aligned.apk
/usr/local/lib/android/sdk/build-tools/29.0.3/apksigner sign --ks app/build/outputs/apk/debug/signingKey.jks --ks-key-alias  --ks-pass pass: --out app/build/outputs/apk/debug/app-debug-signed.apk app/build/outputs/apk/debug/app-debug-aligned.apk
Failed to load signer "signer #1"
java.io.IOException: Short read of DER length
	at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:584)
	at java.base/sun.security.util.DerValue.init(DerValue.java:411)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:352)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:365)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1973)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
Error: The process '/usr/local/lib/android/sdk/build-tools/29.0.3/apksigner' failed with exit code 2

**Comment by paphonb** [comment]
You'll have to create your own signing key and add it to secrets.

**Comment by blogmangit** [comment]
> You'll have to create your own signing key and add it to secrets. 

could you please elaborate how to do that as I am also facing the same issue and there are lots of pr pending so I am merging those pr in my own fork and creating debug apk

**Comment by blogmangit** [comment]
> Building an apk on my own fork isnt working fork: [flug8/lawnicons ](https://github.com/flug8/lawnicons/)
> 
> ![Screenshot_20220627-150138_Chrome](https://user-images.githubusercontent.com/80972789/175948734-7dce49ea-d55c-4733-a1cf-c4224aac33cf.jpg)
> 
> > /usr/bin/cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-aligned.apk
> > /usr/local/lib/android/sdk/build-tools/29.0.3/apksigner sign --ks app/build/outputs/apk/debug/signingKey.jks --ks-key-alias  --ks-pass pass: --out app/build/outputs/apk/debug/app-debug-signed.apk app/build/outputs/apk/debug/app-debug-aligned.apk
> > Failed to load signer "signer #1"
> > java.io.IOException: Short read of DER length
> > at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:584)
> > at java.base/sun.security.util.DerValue.init(DerValue.java:411)
> > at java.base/sun.security.util.DerValue.(DerValue.java:352)
> > at java.base/sun.security.util.DerValue.(DerValue.java:365)
> > at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1973)
> > at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
> > at java.base/java.security.KeyStore.load(KeyStore.java:1479)
> > at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353)
> > at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
> > at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
> > at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277)
> > at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
> > Error: The process '/usr/local/lib/android/sdk/build-tools/29.0.3/apksigner' failed with exit code 2

Do this 
1. install Java (jdk) on windows
2. open command promt
3. cd to java path in my case C:\Program Files\Java\jdk-18.0.1.1\bin
4. create a keystore folder on desktop
5. then type keytool.exe -genkey -v -keystore C:\Users\user\Desktop\Keystore -keyalg RSA -keysize 2048 -validity 10000 -alias debug
6. Download Base 64 utility and extract it to C:\Bin(Create folder Bin)
7. cd to C:\bin
8. then type base64.exe C:\Users\user\Desktop\debug.jks > C:\Users\user\Desktop\debug.jks.base64
9. now open debug.jks.base64 with notepad and copy all contents.
10. Go to forked repository on github.
11. under repository Settings tab go to secrets>action
12. create new repository secrets separately 
a. KEYSTORE (paste contents of debug.jks.base64)
b. KEYSTORE_PASSWORD
c. KEY_ALIAS
d. KEY_PASSWORD 
13. Now build your debug apk.

Regards.
