### ISSUE TITLE
Icon request add icon for pix wallpapers

### ISSUE THREAD

**Issue by Seandylan123** [LawnchairLauncher/lawnicons#603]
Hello there is a missing icon for pix wallpapers my favorite wallpaper app so can you please send out the latest debug apk so that i can download it

Thank you to the lawnchair developers also here's the package name com.pashapuma.pix.wallpapers

**Comment by patrykmichalik** [comment]
Hello! For icon requests, please use this form: https://forms.gle/Fx8vZAiWdW1Tyjo57. Thanks!

**Comment by Seandylan123** [comment]
> Hello! For icon requests, please use this form: https://forms.gle/Fx8vZAiWdW1Tyjo57. Thanks!

Ok i'll do it thanks

**Comment by Seandylan123** [comment]
> Hello! For icon requests, please use this form: https://forms.gle/Fx8vZAiWdW1Tyjo57. Thanks!

Requested thanks
