### ISSUE TITLE
Tachiyomi Icon

### ISSUE THREAD

**Issue by nekoxneko12** [LawnchairLauncher/lawnicons#612]
Tachiyomi is a famous manga reader app which is open source also. Request to add the icon

**Comment by MasterOfBob777** [comment]
In addition to this, possibly add TachiyomiSY as well? Not sure if this qualifies for another issue.

**Comment by koukichi7010** [comment]
>Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required.


I already did tachiyomi and tachiyomiJ2K...unfortunately i didn't do SY and the other fork as im not using them

**Comment by SuperDragonXD** [comment]
Closing since icon requests now go to the forms as stated in the above message:
> > Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required.
