### ISSUE TITLE
Some public apps icons

### ISSUE THREAD

**Issue by ariqren** [LawnchairLauncher/lawnicons#632]
- eu.thedarken.sdm (Sd Maid)
 - com.waze (Waze)
 - com.utorrent.client (uTorrent)
 - com.gorgeous.liteinternational (uLike)
 - devian.tubemate.v3 (Tubemate)
 - com.keramidas.TitaniumBackup (Titanium backup)
 - com.google.android.apps.paidtasks (Rewards)
 - com.catchingnow.icebox (icebox)
 - com.oasisfeng.greenify (Greenify)
 - org.adaway (Adaway)
 - com.adguard.android (Adguard)

**Comment by aDifferentBook** [comment]
Icon request submitted from Google form.

**Comment by Chefski** [comment]
Closing add the icon request is available on the form
