### ISSUE TITLE
some icons to add

### ISSUE THREAD

**Issue by AntogamerYT** [LawnchairLauncher/lawnicons#633]
-  it.owlgram.android (owlgram)
- com.epicgames.fortnite (fortnite)
- com.anydesk.anydeskandroid (anydesk)
- it.homobile.ho (ho.) (it's the app of an italian internet provider)
- at.paysafecard.android (paysafecard)
- com.google.android.apps.walletnfcrel (google wallet)
- org.adaway (adaway)
- com.empat.wory (obimy)
- com.xiaomi.wearable (mi fitness)
- com.supercell.clashroyale (clash royale)
-

**Comment by CarlosRgoku** [comment]
com.tencent.mm ( wechat )
com.tencent.tmgp.cod ( call of duty mobile chinês )
zombie.survival.craft.z ( last day on earth )
com.global.datealive.gp ( date a live: Spirit pledge HD )
com.kwai.video ( Kwai )
br.com.meuanimetv ( AnimeTV )
com.crunchyroll.crunchyroid ( crunshyroll )

**Comment by Guray00** [comment]
com.streetwriters.notesnook (Notesnook)
com.todoist (Todoist)

**Comment by aDifferentBook** [comment]
* com.xodo.pdf.reader [Xodo PDF Reader & Editor](https://play.google.com/store/apps/details?id=com.xodo.pdf.reader)

* com.rhmsoft.edit.pro [QuickEdit Text Editor Pro](https://play.google.com/store/apps/details?id=com.rhmsoft.edit.pro)

* com.rhmsoft.edit [QuickEdit Text Editor](https://play.google.com/store/apps/details?id=com.rhmsoft.edit)

* com.wb.clipboard.pro [Clipto - Organize Any Data](https://play.google.com/store/apps/details?id=com.wb.clipboard.pro)

* com.delphicoder.flud.paid [Flud (Ad free)](https://play.google.com/store/apps/details?id=com.delphicoder.flud.paid)

* com.delphicoder.flud [Flud Torrent Downloader](https://play.google.com/store/apps/details?id=com.delphicoder.flud)

**Comment by Chefski** [comment]
> com.streetwriters.notesnook (Notesnook) com.todoist (Todoist)

Added both #654

**Comment by Chefski** [comment]
> * com.xodo.pdf.reader [Xodo PDF Reader & Editor](https://play.google.com/store/apps/details?id=com.xodo.pdf.reader)
> 
>     * com.rhmsoft.edit.pro [QuickEdit Text Editor Pro](https://play.google.com/store/apps/details?id=com.rhmsoft.edit.pro)
> 
>     * com.rhmsoft.edit [QuickEdit Text Editor](https://play.google.com/store/apps/details?id=com.rhmsoft.edit)
> 
>     * com.wb.clipboard.pro [Clipto - Organize Any Data](https://play.google.com/store/apps/details?id=com.wb.clipboard.pro)
> 
>     * com.delphicoder.flud.paid [Flud (Ad free)](https://play.google.com/store/apps/details?id=com.delphicoder.flud.paid)
> 
>     * com.delphicoder.flud [Flud Torrent Downloader](https://play.google.com/store/apps/details?id=com.delphicoder.flud)

Added all #658

**Comment by cremedemarrons** [comment]
- eu.kanade.tachiyomi (tachiyomi on fdroid)
- me.hackerchick.catima (catima on fdroid)
- me.proton.android.calendar (proton calendar)
