### ISSUE TITLE
Lawnicons detected as Trojan (Oppo/Avast)

### ISSUE THREAD

**Issue by FranzNic** [LawnchairLauncher/lawnicons#634]
Oddly enough, I can't access my payment apps without deleting Lawnicons, as the system antivirus detects the app as Trojan.

Device: OPPO A12 (CPH2083)
Android Version: 9 Pie (ColorOS 6.1, January 2022 security patch)
Lawnicons version: 1.0.0
Antivirus software: Oppo/Avast (built in)

**Comment by somu1795** [comment]
https://www.virustotal.com/gui/file/a8166dffc0ff3848ba58383b18aa73d9c4e6d98f7270a1599faac5800ef903a2/behavior
The virustotal report

**Comment by aDifferentBook** [comment]
> https://www.virustotal.com/gui/file/a8166dffc0ff3848ba58383b18aa73d9c4e6d98f7270a1599faac5800ef903a2/behavior
> The virustotal report

Why are you using apkmirror apk instead of GitHub released apk?

`app_lawnchair_lawnicons_1_1_0_2_minAPI26nodpi_apkmirror_com. apk`

**Comment by Chefski** [comment]
> Oddly enough, I can't access my payment apps without deleting Lawnicons, as the system antivirus detects the app as Trojan.
> 
> Device: OPPO A12 (CPH2083) Android Version: 9 Pie (ColorOS 6.1, January 2022 security patch) Lawnicons version: 1.0.0 Antivirus software: Oppo/Avast (built in)

Did you directly from Github? As @aDifferentBook mentioned, the apkmirror version of Lawnicons is detected as malicous. Please use the [Github version](https://github.com/LawnchairLauncher/lawnicons/releases/tag/v1.1.0) if you haven't yet and return to Github to download the next releases in the future

**Comment by FranzNic** [comment]
Yes, I did. I have escalated this issue on the Telegram chat before.

**Comment by FranzNic** [comment]
Here's the screenshot of the download. (Debug APK)

![Screenshot_2022-09-20-20-09-31-02](https://user-images.githubusercontent.com/57134337/191254056-4a3a3e0f-99a3-4811-94af-fd6b020f1663.jpg)

**Comment by Chefski** [comment]
Latest release of Lawnicons doesn't have anything:
![image](https://user-images.githubusercontent.com/100310118/191328021-db090c00-bafa-40be-881b-4c05d35d2cd4.png)
