### ISSUE TITLE
Enhancement : Oxygen OS 12 Dialer

### ISSUE THREAD

**Issue by bappa555** [LawnchairLauncher/lawnicons#636]
![Screenshot_2022-08-20-10-33-02-79_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/29393112/185729807-400f7e8c-a400-4215-b088-4ba8052ffecd.png)
### About this discussion

On Oxygen OS 12, stock dialer icon is appearing contact icon, can any one fix this.

**Comment by Chefski** [comment]
I don't have the stock OnePlus contacts and phone app anymore but I think this happens because the phone app is connected to the contacts app. When you delete contacts, phone also gets deleted. Both package names are `com.android.contacts` if I remember correctly

**Comment by bappa555** [comment]
Yes it is available for old models like OnePlus 8. And yes you are correct
it is the same app. But other icon packs are manage to present the icons
separately.

**Comment by Chefski** [comment]
> But other icon packs are manage to present the icons separately.

Not sure how other icon packs do it but I know that Delta icons uses a different way of applying the icons to the apps. Lawnchair uses a different method than Delta icons so that might be the problem
