### ISSUE TITLE
Contributors access to Lawnicons icon request forms

### ISSUE THREAD

**Issue by Chefski** [LawnchairLauncher/lawnicons#661]
### About this discussion

Is there a place where icon contributors can see the icons which have been requested or is it only available to mods?

**Comment by aDifferentBook** [comment]
I think all the people create new issue for icon request. Instead of that we need a pinned post where people can submit icon request and developers will have one place to see and complete them.

**Comment by SuperDragonXD** [comment]
There isn't really a public place for the icons, but you can ask paphomb to create a spreadsheet and make it viewable to the public.

/cc @paphonb

**Comment by SuperDragonXD** [comment]
Btw, the sheets file is now publicly accessible in README: https://github.com/LawnchairLauncher/lawnicons/commit/0df8a951dcb9d2593b66c8281a6918caa026c153
