### ISSUE TITLE
[DISCUSSION] Translation

### ISSUE THREAD

**Issue by daywalk3r666** [LawnchairLauncher/lawnicons#681]
### About this discussion

Is a translation necessary for the app?

**Comment by aDifferentBook** [comment]
I don't think so we need it as Lawanicons is a supportive app for Lawnchair but if you want to contribute in translation then you can do it for [Lawnchair](https://github.com/LawnchairLauncher/lawnchair) app itself.

**Comment by Chefski** [comment]
Although lawn icons won't strongly benefit from translations, I think it's something that can be done just to improve it. It only has about 10 strings to be translated in `app/src/main/res/values/strings.xml`.

**Comment by daywalk3r666** [comment]
ok thx
