### ISSUE TITLE
[BUG] Flud (Ad Free) merged in PR #658 but showing normal icon in debug apk

### ISSUE THREAD

**Issue by aDifferentBook** [LawnchairLauncher/lawnicons#684]
### About this discussion

I [requested ](https://github.com/LawnchairLauncher/lawnicons/issues/633#issuecomment-1246662341)  some themed icons and they successfully got [merged in PR #658](https://github.com/LawnchairLauncher/lawnicons/pull/658) thanks to all developers.
I tried to install latest [debug apk (workflow run #364)](https://github.com/LawnchairLauncher/lawnicons/actions/runs/3098677506), all requested icons are showing as expected but only Flud (Ad Free) shows as normal icon.

* Flud (Ad Free) - com.delphicoder.flud.paid

![IMG_20220922_223644_515](https://user-images.githubusercontent.com/80353171/191809119-da82a4b4-ddc5-461d-88dc-4d63ccf21c93.jpg)

@Chefski

**Comment by Chefski** [comment]
Do you know if the free version of flood also has the normal icon?

**Comment by aDifferentBook** [comment]
> Do you know if the free version of flud also has the normal icon?

I just downloaded Flud from Play Store and it also showing normal icon.

See the attached screenshot for both versions.

![IMG_20220923_201807_333.jpg](https://user-images.githubusercontent.com/80353171/191988613-b095884b-4130-475a-abf5-5e6aa0518987.jpg)

**Comment by Chefski** [comment]
Weird, both apps have their lawnicons linked. Maybe someone else will known whats up
