### ISSUE TITLE
[DISCUSSION] Was reverting the Google Wallet icon intentional?

### ISSUE THREAD

**Issue by dercodeling** [LawnchairLauncher/lawnicons#699]
### About this discussion

This is just something I noticed looking through the changes of @SuperDragonXD's recent commit `General SVG cleanup + …` (`e5f97b77b6f057b688fd680a2425e69ecd4a1eea`): there were previously two references to the Google Wallet app (`com.google.android.apps.walletnfcrel`), one with the old Google Pay logo and one with the new Google Wallet logo, and the latter was removed, leaving the out of date icon as the current linked icon. Was this intentional? If it is, that's fine, just thought I'd ask as I could see it being unintentional, especially as the Google Wallet SVG file is still there.
Thanks!

**Comment by SuperDragonXD** [comment]
Thanks for the heads-up! Fixed.
