### ISSUE TITLE
Suggestions. 

### ISSUE THREAD

**Issue by Blank-Slate7** [LawnchairLauncher/lawnicons#712]
### About this discussion

Hello, I would like to give some recommendations on lawnicons and what icons to add, you can decide to ignore it if you want but here are my thoughts. 

1. Add support for android/OEM Icons. Some android apps unsupported include Device care, Digital wellbeing, etc. 
   Some OEM apps not included by Lawnicons are Galaxy Wearable, Mi store, Samsung Finder, Samsung Cloud, etc. 
   Without these simple android/OEM app icon support, Lawnicons will look uncompleted to the user. 
2. Add support for apps many people use on their phones. For example, Formula 1, Formula E, Microsoft Apps, religious 
   apps like Bible, etc. 
3. Add icons for Open source apps. Some of these apps include Libchecker, etc. 
4. Please get inspiration from other monet-themed icon packs. I am not saying you should copy the icons, just see how these 
    icons are made and then rearrange and modify them to lawnicons guidelines

As a general user of Lawnchair and Lawnicons [in fact, I am using the new one with 569 icons on board], these are my suggestions to the lawnicons developers, and with these suggestions I am doubly sure that lawnicons will be a more complete icon pack for lawnchair that's good to use. 

Thoughts?

**Comment by Chefski** [comment]
I'll be closing this issue. Feel free to [request](https://docs.google.com/forms/d/e/1FAIpQLSeiRgR6nTnS0AdhnZn4ypR37yjWe3c3z_YmjqiL-O8f7oqaTw/viewform) icons that have not yet been added. Although they may not be made straight away, someone may eventually make them. Thanks for the recommendations :)
