### ISSUE TITLE
[DISCUSSION] 99 app icon is too big

### ISSUE THREAD

**Issue by VHUGO98** [LawnchairLauncher/lawnicons#743]
### About this discussion

the 99 icon is too big, needs to be adjusted.
![Screenshot_20221009-173219](https://user-images.githubusercontent.com/33030712/194778255-4d3ba837-a5a7-4a4c-b4ce-5ab9fd118bf2.png)

**Comment by Chefski** [comment]
Is this referring to the overall shape of the whole icon or just whats inside the square-circle?
@VHUGO98

**Comment by VHUGO98** [comment]
> Is this referring to the overall shape of the whole icon or just whats inside the square-circle? @VHUGO98

He's bigger than the others in general.

**Comment by Chefski** [comment]
Same issue as in #230?

**Comment by VHUGO98** [comment]
> Same issue as in #230?

I found that enabling the adaptive icons function the problem with the icon is solved, but it is the same problem reported in #230

**Comment by Chefski** [comment]
I'll be closing this issue as its a duplicate. Wasn't sure if the adaptive icons method actually works but I guess it does. This issue happens because of scaling done by the launcher as stated [here](https://github.com/LawnchairLauncher/lawnicons/issues/444#issuecomment-1261376490).
