### ISSUE TITLE
[DISCUSSION] Geometric Weather

### ISSUE THREAD

**Issue by daywalk3r666** [LawnchairLauncher/lawnicons#755]
### About this discussion

i found this duplicate but i don't know which i should delete
![image](https://user-images.githubusercontent.com/15938117/197111351-5902067a-1445-42f7-b635-1bbed29ac22f.png)
![image](https://user-images.githubusercontent.com/15938117/197111401-1729dc3d-586b-48e8-a57d-51950e4abc75.png)

**Comment by SuperDragonXD** [comment]
You can delete the bottom one (`<icon drawable="@drawable/weather" ...>`), since it uses the generic weather icon.
