### ISSUE TITLE
[Contributing] Can you link a tutorial on how to redesign an icon in SVG? 

### ISSUE THREAD

**Issue by peterge1998** [LawnchairLauncher/lawnicons#766]
### About this discussion

![image](https://user-images.githubusercontent.com/47355238/197953146-a8ebe3e6-d7d9-4347-a117-b49548dd6822.png)
![bandsintown](https://user-images.githubusercontent.com/47355238/197952671-bc2b2d33-9346-4b51-a4dd-20d900d24c64.png)

I was able to do this with GIMP based on this [video](https://youtu.be/HPGvrxjT7aY), but it's not SVG and corner radius isn't considered, tho. (But I already like how it looks :D) Converting it to SVG with an online converter is doing bad.

I guess I should use Inkscape for this? Could you please link/add to Contributing.md a tutorial video for me which explains what I should do? I am new to vector design but would like to learn about it.

**Comment by peterge1998** [comment]
`autotrace bandsintown.png --output-file output.svg --output-format svg`

Autotrace is doing weird things too...

![output](https://user-images.githubusercontent.com/47355238/197953920-2c94e8b5-34ff-407a-8e5d-35eee285ddfa.svg)

**Comment by Chefski** [comment]
I see you're having some issues with making icons. [Here's](https://www.loom.com/share/1c71afe711fb4be2b1b27c166b0499bb) a short clip of me using the pen tool to create a section of the icon you were making here. However I use Illustrator to create icons instead of Inkscape so its a bit different. If I'm not wrong, Inkscape has a "bezier tool" instead of "pen tool". I'd recommend watching a video on learning the bezier. Here's a video of a person making a music icon using the bezier and circle tool: https://www.youtube.com/watch?v=wH7OI5r8lfU
The pen/bezier tool is something you learn and improve on by using. I hope this helps and I'll take note of making a tutorial video for the future.

**Comment by peterge1998** [comment]
Thanks for your help @Chefski, I found [this](https://youtu.be/ABVLbqeZO6Q) tutorial which was helpful to begin learning the bezier pen. I was able to do this with it, which looks quite useful already!
![bandsintown](https://user-images.githubusercontent.com/47355238/198960815-bfac3056-2676-442c-8f3f-8f0261d87323.svg)

What do you say? :D

I would like to keep focus on FOSS tools like Inkscape for now, because I don't own Adobe Suit.

**Comment by peterge1998** [comment]
I am still missing the Stroke width of 12 px, as set in CONTRIBUTING.md. The image my comment above is with a stroke style width of 1 px. This is what 12 px in Inkscape looks like:
![image](https://user-images.githubusercontent.com/47355238/199015001-c38929d0-02f5-47b0-9b0e-67d6d423185a.png)
Should I go with 6 in Inkscape? Or what would be correct?

Really looking into making some icons :eyes:

**Comment by Chefski** [comment]
Great to see you learned how to make vector icons! I'd suggest moving the lines more inwards if they seem to touch other lines after applying the stroke. Check out my [sample](https://github.com/LawnchairLauncher/lawnicons/files/9905004/sample.svg.zip) here. I maintained the 12px stroke by putting the path more inwards if that makes sense. Feel free to use that SVG and make a PR :)

Good luck!

**Comment by peterge1998** [comment]
Where do you get the original icon in 192x192 from @Chefski ? If I look on play.google.com, they are 240x240 like [this](https://play-lh.googleusercontent.com/d4HyvRGWXKvEOc7HAROImJdf_OSs3lQsYbtE1P5T__znXk5nBOxrtGiNzYwaj9Ca_Ow0=w240-h480). Or do you just resize them yourself?

**Comment by Chefski** [comment]
You resize yourself. I also get the icons from the Play Store website.

**Comment by peterge1998** [comment]
Okay, thats what i tried to do (scale pure icon to 160x160 with kpaint and then resize to 176x176 for left and bottom 16px ((192-160)/2), then rotating by 90° 2 times and resizing to 192x192 and rotating so that in the end my icon size is 192x192 with 16px borders.)

What tool did you use for the red lines in the pr?
Are these px values for the red lines correct?
       16 28 164 176
16
28
164
176

**Comment by Chefski** [comment]
When I make the icons and have to resize to fit the borders, I group all the shapes and make either the height or width (which ever is bigger) 148px if the stroke is made from the center.
![image](https://user-images.githubusercontent.com/100310118/199468683-96b5db81-da21-48f5-accc-34371bdfa0bf.png)


The red lines are guide lines. I have them set to 160x160px and 144x144px as those are the 2 content area sizes specified in the guidelines. 160x160px is for most shapes, 144x144px is for squares.

https://inkscapetutorials.wordpress.com/2014/04/25/working-with-guides-in-inkscape/

These guidelines were also present in the Loom clip but they were cyan and I put them at at each line I had to draw

**Comment by peterge1998** [comment]
> 144x144px is for squares.

What does that mean? Could you link an example, please?

**Comment by Chefski** [comment]
Instagram uses the 144x144px content area as its a square but a very rounded one

![image](https://user-images.githubusercontent.com/100310118/199835877-c534e847-4380-4f33-ad59-abec297f2948.png)
