### ISSUE TITLE
Add some icons

### ISSUE THREAD

**Issue by lilyoo226** [LawnchairLauncher/lawnicons#77]
app:Contacts
package:com.android.contacts
Launcher:com.android.contacts.activities.PeopleActivity
app:Phone
package:com.sh.smart.caller
Launcher:com.android.dialer.main.impl.MainActivity
app:My Vodafone
package:com.myvodafone.app
Launcher:com.myvodafone.app.MainActivity
app:Twi Bible
package:com.mobobi.twibible
Launcher:com.mobobi.twibible.SplashActivity
app:Doodle
package:xyz.zedler.patrick.doodle
Launcher:xyz.zedler.patrick.doodle.activity.SplashActivity
app:Xender
package:cn.xender
Launcher:cn.xender.ui.activity.SplashActivity
app:Camera
package:com.transsion.camera
Launcher:com.android.camera.CameraLauncher
app:ADM
package:com.dv.adm
Launcher:com.dv.get.Main
app:Calculator
package:com.transsion.calculator
Launcher:com.transsion.calculator.Calculator
app:Face Unlock
package:com.transsion.faceid
Launcher:null
app:FM Radio
package:com.funbase.xradio
Launcher:com.funbase.xradio.home.activity.MainActivity
app:Carlcare
package:com.transsion.carlcare
Launcher:null
app:BlockerX
package:io.funswitch.blocker
Launcher:io.funswitch.blocker.activities.SplashScreenActivity
app:Face Unlock
package:com.transsion.faceidsub
Launcher:com.transsion.faceid.FaceManagerActivity
app:ZArchiver
package:ru.zdevs.zarchiver
Launcher:ru.zdevs.zarchiver.ZArchiver
app:Hago
package:com.yy.hiyo
Launcher:com.yy.hiyo.MainActivity

**Comment by arun54321** [comment]
My vodafone [svg](https://katb.in/oduposojabo)

android [vector ](https://katb.in/yohetesahux)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
