### ISSUE TITLE
New icons requested priority

### ISSUE THREAD

**Issue by chanh2018** [LawnchairLauncher/lawnicons#771]
### About this discussion

Will new icons requested be added due to "first come first serve" in queue or just randomly picked by developers?

**Comment by Chefski** [comment]
They'll most likely be picked randomly. The newest requests are always at the bottom of the list. We don't have any rules set that newest requests should be done first. It depends on the contributor whether they decide to make newly requested icons or a random request in the middle of the form.

**Comment by chanh2018** [comment]
Thank you for quick response.I wish someone will pick my request that I submitted long time ago for these two icons:
Password Safe:  com.reneph.passwordsafePassword Safe and Manager - Apps on Google Play


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Password Safe and Manager - Apps on Google Play

Offline password manager to securely store passwords, logins and more.
 |

 |

 |



Bills Reminder:  in.usefulapp.timelybillsBills Reminder, Budget Planner - Apps on Google Play


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Bills Reminder, Budget Planner - Apps on Google Play

Bill payment organizer, payment tracker with budgeting & bill reminders
 |

 |

 |




Regards,
Chanh Nguyen 

    On Thursday, October 27, 2022 at 04:11:41 PM PDT, Patryk Radziszewski ***@***.***> wrote:  
 
 


They'll most likely be picked randomly. The newest requests are always at the bottom of the list. We don't have any rules set that newest requests should be done first. It depends on the contributor whether they decide to make newly requested icons or a random request in the middle of the form.

**Comment by Chefski** [comment]
I'll check out the request when I have time :)  I'll be closing the issue now.

**Comment by chanh2018** [comment]
Dear Patryk,
Thank you so much for your help.I couldn't believe my eyes when seeing my two requested icons added.I really appreciate that.
Regards,
Chanh Nguyen 

    On Thursday, October 27, 2022 at 05:42:50 PM PDT, Patryk Radziszewski ***@***.***> wrote:  
 
 


Closed #771 as completed.
