### ISSUE TITLE
[Contributing] How to design icons with pointed tips?

### ISSUE THREAD

**Issue by peterge1998** [LawnchairLauncher/lawnicons#802]
### About this discussion

How do I design icons like for pointed tips like the Eventim, freenet or Magic Arena logo?
![image](https://user-images.githubusercontent.com/47355238/200157702-d442bb2f-a221-4fb5-a7db-151ecc5e2060.png)
![image](https://user-images.githubusercontent.com/47355238/200169008-fc775045-6503-4179-9eec-e6ae2953592e.png)
![image](https://user-images.githubusercontent.com/47355238/200157710-a59111ee-b053-4a34-8c94-c34a699fee5c.png)

I am no English native, sorry if pointed tip is the wrong description for this kind of tips :D

**Comment by Chefski** [comment]
Hey! 

When it comes to sharp tips, the rounded corners in stroke settings should make the corners rounded. The stroke must be set to centred though. I made the 2 top logo's if you'd like to check them out. They're ready to be PR'd if you'd like:

[eventim.svg.zip](https://github.com/LawnchairLauncher/lawnicons/files/9946136/eventim.svg.zip)
[freenet.svg.zip](https://github.com/LawnchairLauncher/lawnicons/files/9946137/freenet.svg.zip)

I use Adobe Illustrator so this might not be helpful but here's how I made Eventim. I made a square, put 4 circle at each corner which have a radius half of the square, then use shape build tool to cutout the path of the circle from the square.

The shapes you provided are a bit complicated as they will require you to curve the lines. It's trial and error with making curves. You can watch a video on making curves with the Bezier tool if you'd like. 

Hope this answers your question and maybe helps a bit.
I'll close this issue but you can open it again if you have any other questions relating to this
