### ISSUE TITLE
[DISCUSSION] Change the design of these icons?

### ISSUE THREAD

**Issue by peterge1998** [LawnchairLauncher/lawnicons#808]
### About this discussion

I have designed some icons now, but i am no artist or a design expert. BUT I would change these icons a little bit:

1. Threema
https://github.com/LawnchairLauncher/lawnicons/blob/ae61cb113585ebafd74fade576db5bbdaf97739f/svgs/threema.svg
![image](https://user-images.githubusercontent.com/47355238/200398767-be1e6191-f0eb-4c9c-9bb2-2f423be0b839.png)
I would change the icon to make the lock and the chat bubble a little bit smaller and add the three dots, typical for Threemas icon.

2. Spotify
https://github.com/LawnchairLauncher/lawnicons/blob/ae61cb113585ebafd74fade576db5bbdaf97739f/svgs/spotify.svg
![image](https://user-images.githubusercontent.com/47355238/200398986-490ba48d-3792-41f7-8728-1d6ea2af2efd.png)
I would increase the stroke width for each line like in the original icon to have more of spotifys original design.

3. mydealz
https://github.com/LawnchairLauncher/lawnicons/blob/ae61cb113585ebafd74fade576db5bbdaf97739f/svgs/mydealz.svg
Its no outline icon...

4. Covpass
https://github.com/LawnchairLauncher/lawnicons/blob/ae61cb113585ebafd74fade576db5bbdaf97739f/svgs/covpass.svg
Same like 3. ...

While I can provide the design for 1 & 2, 3 & 4 seen very complex. But I can try.
I open this issue because I want to discuss it before opening a PR. Maybe you have different opinions on this.

Btw whats with etar (the calender icon)?

**Comment by Chefski** [comment]
1. Sure, feel free to change it.
2. Making each stroke width different wouldn't suit the Lawnicons design style as it only uses 12px and 8px. 
3. Some icons still use the old design style so feel free to change all other ones that also use a fill style.
4. Same as 3

You can open a PR for any icon you redesign and maintainers will review to decide whether its a suitable change or not :) No need to ask for permission

Etar got removed as all static icons got removed from Lawnicons and are now part of the dynamic icons built into Lawnchair
https://github.com/LawnchairLauncher/lawnchair/pull/3038

**Comment by peterge1998** [comment]
Would you accept sth like 3 stroke width for spotify like this for each of the three lines:
12px
10px
8px

**Comment by Chefski** [comment]
The Spotify icon will remain as it is
