### ISSUE TITLE
Samsung Internet icon could be bigger

### ISSUE THREAD

**Issue by rufus582** [LawnchairLauncher/lawnicons#88]
The newly added samsung internet themed icon seems to be comparatively smaller than the other icons. I feel it could be slightly bigger to match the size of the other icons. 

![Screenshot_20211115-204605_Lawnchair](https://user-images.githubusercontent.com/68699122/141807137-f7c825b1-7952-4ffb-91f2-81b3a6f1c217.jpg)
See the above screenshot for reference. You can see samsung internet icon is comparatively small. Hope this gets fixed soon😊

**Comment by arun54321** [comment]
I don't think so. It is already 20px wide. 
See this https://github.com/LawnchairLauncher/lawnicons/blob/master/contributing-image-1.png

**Comment by arun54321** [comment]
![image](https://user-images.githubusercontent.com/42943340/141992478-87a05ad0-370e-444e-8719-c632c0aae3ff.png)

**Comment by rufus582** [comment]
I do respect those guidelines, but I hope you could also see the difference in icon size of play store along with the other icons, and this samsung internet icon. I feel it could be a bit bigger tho😑

By the way, may I ask which software you use to make these type of icons?

**Comment by arun54321** [comment]
If you measure it, it's actually wider than play store icon.

**Comment by arun54321** [comment]
If you want bigger samsung icon, you can get it from [here.](https://github.com/arun54321/lawnicons/blob/2fddc6eacb10a4fd82bba2a6453d49a31925e448/app/src/main/res/drawable/sbrowser.xml)

**Comment by ninopiamonte** [comment]
What do you guys think of this tweak? 
![image](https://user-images.githubusercontent.com/88925766/142168142-7b19b55a-2a2b-4686-bc39-04fa8a6609a2.png)

**Comment by rufus582** [comment]
> If you measure it, it's actually wider than play store icon.

I'm not talking about the measurements, but the look. I felt the icon was smaller, when looking with our eyes😑

**Comment by rufus582** [comment]
> If you want bigger samsung icon, you can get it from [here.](https://github.com/arun54321/lawnicons/blob/2fddc6eacb10a4fd82bba2a6453d49a31925e448/app/src/main/res/drawable/sbrowser.xml)

I don't understand that🤔🤔🤔

**Comment by rufus582** [comment]
> What do you guys think of this tweak? ![image](https://user-images.githubusercontent.com/88925766/142168142-7b19b55a-2a2b-4686-bc39-04fa8a6609a2.png)

Nice, but minor tweaks needed😑

**Comment by rufus582** [comment]
> What do you guys think of this tweak? ![image](https://user-images.githubusercontent.com/88925766/142168142-7b19b55a-2a2b-4686-bc39-04fa8a6609a2.png)

Nice, but minor tweaks needed😑
![Screenshot_20211117-144042_Chrome](https://user-images.githubusercontent.com/68699122/142171231-19244d1f-6aa0-4d54-a40d-8232095193a1.jpg)

**Comment by ninopiamonte** [comment]
<img width="336" alt="Screen Shot 2021-11-17 at 05 25 50 PM" src="https://user-images.githubusercontent.com/88925766/142173579-dca19de7-6edd-472d-b3e3-ef45fc994c5a.png">

**Comment by Chefski** [comment]
Case can be closed as we have a valid Samsung Internet icon
@SuperDragonXD 
<img src="https://user-images.githubusercontent.com/100310118/191033445-579620c5-320e-4883-bd1e-a1ba78520d5a.png" width=300 />
