### ISSUE TITLE
[DISCUSSION] How can icons with different colours be improved?

### ISSUE THREAD

**Issue by peterge1998** [LawnchairLauncher/lawnicons#946]
### About this discussion

The mydealz icon i did back then looks like shit. There is no contrast in it, which makes the original icon look food (green, black, white).
How can i improve the icon which i did design?

**Comment by peterge1998** [comment]
Maybe different stroke with for different colours (like the eyes)?

**Comment by peterge1998** [comment]
Okay, after I changed the dots and the width of the eyes & teeth, it looks way better :
https://github.com/LawnchairLauncher/lawnicons/pull/944/commits/df40f74d40c8917a521c4164b442a162dca13a67

**Comment by Chefski** [comment]
It's quite hard to show contrast with just lines that are black. I don't think the colour in icons really matters as the icons are the outlines rather than the solids inside the outline. I think the redesign looks better.

**Comment by peterge1998** [comment]
It definetly does. Now I am happy :)
