### ISSUE TITLE
Problem with icons applying

### ISSUE THREAD

**Issue by Vijorich** [LawnchairLauncher/lawnicons#951]
### About this discussion

Why do some icons not change even though they are in the icon pack and all links are correct?

https://user-images.githubusercontent.com/88296320/210801719-5fb48acb-d24d-4138-a2c9-66834c0516e2.mp4

**Comment by Vijorich** [comment]
Goodline icon also doesn't work properly

**Comment by jacksonwelsh** [comment]
+1, 1password 8 as well. com.1password.android

**Comment by naveenccmsd** [comment]
@Vijorich Can you  share the app component details for the above apps to verify?

you can follow below guid to get it.
https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#using-3rd-party-apps

or below


https://user-images.githubusercontent.com/7315975/214953769-0b5bdc7f-61fa-4c76-a2b6-bc2b38ff2af5.mp4

**Comment by jacksonwelsh** [comment]
For 1password: 

```
<appfilter>

	<!-- 1Password -->
	<item component="ComponentInfo{com.onepassword.android/com.onepassword.android.app.StartActivity}" drawable="1password"/>

</appfilter>
```

**Comment by naveenccmsd** [comment]
@jacksonwelsh , Thank you . I have added link for 1password.

https://github.com/LawnchairLauncher/lawnicons/pull/1002

**Comment by Vijorich** [comment]
> @Vijorich Can you  share the app component details for the above apps to verify?
> 
> you can follow below guid to get it.
> https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#using-3rd-party-apps
> 
> or below
> 
> 
> https://user-images.githubusercontent.com/7315975/214953769-0b5bdc7f-61fa-4c76-a2b6-bc2b38ff2af5.mp4
> 
> 

https://paste.crdroid.net/l4CdeH

https://user-images.githubusercontent.com/88296320/215277431-f765adc8-2cff-4ec4-aa8d-9840c97b51eb.mp4

**Comment by naveenccmsd** [comment]
@Vijorich  I undersnad you were facing issue with icon request app , unfortuanitly it was not owned by lawncher team, we can't fix the issue , without appcomponent details from your mobile we can't fix the icon mapping issue.

Can you try with any other apps and extract the app componenet details ? it should be something like below

<appfilter>

	
	<item component="ComponentInfo{com.onepassword.android/com.onepassword.android.app.StartActivity}" drawable="1password"/>

</appfilter>


Alernativy try the below app and select iconsrequest option 

https://github.com/naveenccmsd/Ayan/releases/download/1.2.2/Ayan_iconpack_v1.2.2.apk or candybar dev in from playstore

**Comment by Vijorich** [comment]
Steam (com.valvesoftware.android.steam.community/com.valvesoftware.android.steam.community.MainActivity) Steam.svg
Goodline (info.goodline.mobile2/info.goodline.mobile2.MainActivity) goodline.svg
FixPrice (ru.bestprice.fixprice/ru.bestprice.fixprice.application.root.MainActivity) FixPrice.svg
Grill one (ru.geo.ppmobile.grillone/ru.geo.ppmobile.grillone.MainActivity) grillone.svg
Eapteka (ru.getpharma.eapteka/ru.getpharma.eapteka.mainscreen.bottom_navigation.MainActivityWithBottomBar) eapteka.svg
Paysphere (ru.nskes.paysphera/ru.nskes.paysphera.presentation_v2.screen.activity.main_activity.MainActivity) paysphera.svg
SGK (ru.sibgenco.general/ru.sibgenco.general.ui.activity.HomeActivity) skg.svg
Riseup VPN (se.leap.riseupvpn/se.leap.bitmaskclient.base.MainActivity) riseup_vpn.svg
Mind Tracker (com.fedosov.mindtracker/com.fedosov.mindtracker.MainActivity) mindtracker.svg
RuStore (ru.vk.store/ru.vk.store.app.MainActivity) rustore.svg
Pyaterochka (ru.pyaterochka.app.browser/ru.pyaterochka.app.browser.BrowserActivity) pyaterochka.svg
Sber mega market (ru.goods.marketplace/ru.goods.marketplace.SingleActivity) sber_mega_market.svg

**Comment by Chefski** [comment]
@Vijorich could you check if all the icons are working as intended now with the latest debug file?

**Comment by Vijorich** [comment]
@Chefski 
![Screenshot_20230313-045131_Sushi Launcher.png](https://user-images.githubusercontent.com/88296320/224575867-279febf0-4f20-478e-91b5-d63d48c32404.png)

3/12

**Comment by daywalk3r666** [comment]
![Screenshot_20230313-072335_Lawnchair (Debug)](https://user-images.githubusercontent.com/15938117/224623279-e68d740c-f0a8-4ec0-adc1-56dfd10ba536.png)

6/9 

I will check if the activities are right and the right drawable are linked

**Comment by daywalk3r666** [comment]
![Screenshot_20230313-081947_Lawnchair (Debug)](https://user-images.githubusercontent.com/15938117/224633429-ed4c0c0b-cdf6-4a2f-9a5d-73fc33bd658f.png)
Test it with this version of lawnchair https://github.com/LawnchairLauncher/lawnchair/commit/44da9e2

Works with kvaesitso launcher too.

**Comment by daywalk3r666** [comment]
@Vijorich can you check the last debug apk

**Comment by Vijorich** [comment]
Still only 3 of 12 for me in both lawnicons and kvaesito![Screenshot_20230314-081131_Sushi Launcher.png](https://user-images.githubusercontent.com/88296320/224866851-b58d1fb1-e71b-4e31-ae7a-32525934a420.png)

![Screenshot_20230314-081117_Sushi Launcher.png](https://user-images.githubusercontent.com/88296320/224866855-98a805e2-7be4-4d5c-810a-0680b0946a0c.png)

![Screenshot_20230314-081134_Sushi Launcher.png](https://user-images.githubusercontent.com/88296320/224866852-5c545a94-4154-4c41-993b-fb73d9e4ab7a.png)

![Screenshot_20230314-081120_Sushi Launcher.png](https://user-images.githubusercontent.com/88296320/224866853-7aad69e7-b0b2-43db-ba2d-88eab76e95af.png)

**Comment by daywalk3r666** [comment]
whats your current lawnchair version? because since lawnicons switched to an icon pack, my app won't work with lawnchair launcher.

**Comment by Vijorich** [comment]
> whats your current lawnchair version? because since lawnicons switched to an icon pack, my app won't work with lawnchair launcher.

![Screenshot_20230314-123825_Sushi Launcher.png](https://user-images.githubusercontent.com/88296320/224906418-b9b4a749-3350-4ffd-b034-8dc31a26ce9b.png)

I have sushi launcher, which was pre installed in rom

**Comment by daywalk3r666** [comment]
Then is launcher rated?

**Comment by KTibow** [comment]
Perhaps a caching issue? Does this happen with a different launcher?

**Comment by PathosEthosLogos** [comment]
> Perhaps a caching issue? Does this happen with a different launcher?

Does not seem to do it. I also tried clearing Lawnchair cache (though not Lawnicons).

Seems to be a well-known problem https://github.com/LawnchairLauncher/lawnicons/issues/1154 https://github.com/LawnchairLauncher/lawnicons/issues/1722

Is this a Lawnchair issue?

Secure Folder and muPDF are not applying for me.

**Comment by x9136** [comment]
I suggest installing [Lawnchair 14 Beta 2](https://lawnchair.app/downloads/), the latest version of Lawnicons, and let us know if the problem still occurs.
