### ISSUE TITLE
F-Droid's Aves gallery doesn't link to Aves' icon

### ISSUE THREAD

**Issue by projjalm** [LawnchairLauncher/lawnicons#994]
The F-Droid's version of Aves gallery, which is stripped off from non-free dependencies, and thus is named `deckers.thibault.aves.libre` by the original author, doesn't link to `deckers.thibault.aves`'s icon, which is available from Gplay (and IzzyOnDroid I think). Therefore, no themed icon appears for the former.  

#993 fixes this, by adding another `<item>` in app/assets/appfilter.xml, which mentions the libre version of Aves and links its drawable to the common `aves_gallery` used for the non-free one.  

Look into this :)

**Comment by Chefski** [comment]
Is the non libre version themed?

**Comment by projjalm** [comment]
> Is the non libre version themed?
Yes, the non-free one was themed properly.  
And now the libre one is too in the latest debug apk.
![deckers thibault aves libre-lawnicons](https://user-images.githubusercontent.com/121298637/215183352-208323f5-25e0-4995-b38c-6f541c006c25.png)
Thanks for the merge :+1:
